// examples/angular/src/app/pages/blog-listing/components/blog-card/blog-card.component.ts
import { Component, computed, input } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { RouterLink } from '@angular/router';
import { editContentlet } from '@dotcms/uve';
import { Blog } from '../../../../shared/contentlet.model';
import { UVE_MODE } from '@dotcms/types';
import { DotCMSShowWhenDirective } from '@dotcms/angular';
@Component({
    selector: 'app-blog-card',
    templateUrl: './blog-card.component.html',
    imports: [RouterLink, NgOptimizedImage, DotCMSShowWhenDirective]
})
export class BlogCardComponent {
    blog = input.required<Blog>();

    UVE_MODE = UVE_MODE;

    editContentlet(blog: Blog): void {
        editContentlet(blog);
    }

    formattedDate = computed(() => this.getFormattedDate(this.blog().modDate));

    getFormattedDate(dateString: string): string {
        const options: Intl.DateTimeFormatOptions = {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        };

        return new Date(dateString).toLocaleDateString('en-US', options);
    }
}

<div
    class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300 relative flex flex-col h-full">
    <ng-template [dotCMSShowWhen]="UVE_MODE.EDIT">
        <button
            (click)="editContentlet(blog())"
            class="absolute top-2 right-2 z-10 bg-red-500 text-white rounded-md py-2 px-4 shadow-md hover:bg-red-600">
            Edit
        </button>
    </ng-template>

    <div class="relative h-48 w-full">
        @if (blog().image) {
        <img
            [ngSrc]="blog().inode"
            [alt]="blog().urlTitle || blog().title"
            fill
            class="absolute inset-0 w-full h-full object-cover" />
        } @else {
        <div class="absolute inset-0 bg-gray-200 flex items-center justify-center">
            <span class="text-gray-400">No image</span>
        </div>
        }
    </div>

    <div class="p-4 flex flex-col grow">
        <h3 class="text-lg font-bold mb-2 hover:text-red-500">
            <a [routerLink]="blog().urlMap">{{ blog().title }}</a>
        </h3>

        @if (blog().teaser) {
        <p class="text-gray-600 text-sm mb-3 line-clamp-2">
            {{ blog().teaser }}
        </p>
        }

        <div class="flex justify-between items-center mt-auto pt-3 border-t border-gray-100">
            <time class="text-sm text-gray-500">
                {{ getFormattedDate(blog().modDate) }}
            </time>
        </div>
    </div>
</div>

// examples/astro/src/components/react/BlogCard.tsx
import { editContentlet } from "@dotcms/uve";
import type { DotCMSBasicContentlet } from "@dotcms/types";
import { useIsEditMode } from "src/hooks/isEditMode";

interface BlogCardProps extends DotCMSBasicContentlet {
  title: string;
  image: string;
  urlMap: string;
  inode: string;
  modDate: string;
  urlTitle: string;
  teaser: string;
}

const dateFormatOptions: Intl.DateTimeFormatOptions = {
  year: "numeric",
  month: "long",
  day: "numeric",
};

export default function BlogCard({ blog }: { blog: BlogCardProps }) {
  const { title, image, urlMap, inode, modDate, urlTitle, teaser } = blog;

  const isEditMode = useIsEditMode();

  return (
    <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300 relative flex flex-col h-full">
      {isEditMode && (
        <button
          onClick={() => editContentlet(blog)}
          className="absolute top-2 right-2 z-10 bg-blue-500 text-white rounded-md py-2 px-4 shadow-md hover:bg-blue-600"
        >
          Edit
        </button>
      )}

      <div className="relative h-48 w-full">
        {image ? (
          <img
            src={`/dA/${inode}`}
            alt={urlTitle || title}
            className="object-cover"
          />
        ) : (
          <div className="absolute inset-0 bg-gray-200 flex items-center justify-center">
            <span className="text-gray-400">No image</span>
          </div>
        )}
      </div>

      <div className="p-4 flex flex-col grow">
        <h3 className="text-lg font-bold mb-2 hover:text-blue-600">
          <a href={urlMap}>{title}</a>
        </h3>

        {teaser && (
          <p className="text-gray-600 text-sm mb-3 line-clamp-2">{teaser}</p>
        )}

        <div className="flex justify-between items-center mt-auto pt-3 border-t border-gray-100">
          <time className="text-sm text-gray-500">
            {new Date(modDate).toLocaleDateString("en-US", dateFormatOptions)}
          </time>
        </div>
      </div>
    </div>
  );
}
