// examples/astro/src/react/layout/header.tsx


function Header({ children }) {
    return (
        <header className="flex items-center justify-between p-4 bg-blue-500">
            <div className="flex items-center">
                <h2 className="text-3xl font-bold text-white">
                    <a href="/">TravelLux</a>
                </h2>
            </div>
            {children}
        </header>
    );
}

export default Header;

// examples/angular-ssr/src/app/components/header/header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

import { ReorderButtonComponent } from '../reorder-button/reorder-button.component';

@Component({
  selector: 'app-header',
  imports: [ReorderButtonComponent, RouterLink],
  template: `
    <header class="flex items-center justify-between p-4 bg-red-400">
      <div class="flex items-center justify-between container mx-auto">
        <h2 class="text-3xl font-bold text-white">
          <a routerLink="/">TravelLux with NG</a>
        </h2>
        <div>
          <app-reorder-button />
          <ng-content />
        </div>
      </div>
    </header>
  `,
  styleUrl: './header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {}
