// core-web/libs/sdk/react/src/lib/next/components/Container/Container.tsx
import { useContext, useRef } from 'react';
import { isInsideEditor } from '@dotcms/client';

import { DotCMSRenderContext, DotCMSRenderContextI } from '../../contexts/DotCMSRenderContext';
import { DotCMSColumnContainer, DotCMSContentlet } from '../../types';
import { getContainersData } from '../../utils/utils';
import { useCheckVisibleContent } from '../../hooks/useCheckHaveContent';

type ContainerProps = {
    container: DotCMSColumnContainer;
};

/**
 * Renders a Container with its content using information provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @export
 * @param {ContainerProps} { containerRef }
 * @return {JSX.Element} Rendered container with content
 */
export function Container({ container }: ContainerProps) {
    const { identifier, uuid } = container;
    const { dotCMSPageAsset, customComponents } = useContext(
        DotCMSRenderContext
    ) as DotCMSRenderContextI;

    const { acceptTypes, contentlets, maxContentlets, variantId, path } = getContainersData(
        dotCMSPageAsset.containers,
        container
    );

    const containerData = JSON.stringify({
        uuid,
        variantId,
        acceptTypes,
        maxContentlets,
        identifier: path ?? identifier
    }); // Get Container

    const isEmpty = contentlets.length === 0;
    const emptyContainerStyle = {
        width: '100%',
        backgroundColor: '#ECF0FD',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#030E32',
        height: '10rem'
    };

    return (
        <div
            data-testid="dot-container"
            data-dot-object="container"
            data-dot-accept-types={acceptTypes}
            data-dot-identifier={path ?? identifier}
            data-max-contentlets={maxContentlets}
            data-dot-uuid={uuid}
            style={isEmpty ? emptyContainerStyle : {}}>
            {isEmpty
                ? 'This container is empty.'
                : contentlets.map((contentlet: DotCMSContentlet) => (
                      <ComponentRender
                          key={contentlet.identifier}
                          contentlet={contentlet}
                          components={customComponents}
                          container={containerData}
                      />
                  ))}
        </div>
    );
}

// MOVE TO ANOTHER FILE
function ComponentRender({ contentlet, container, components }: any) {
    const ref = useRef<HTMLDivElement | null>(null);
    const haveContent = useCheckVisibleContent(ref);

    const ContentTypeComponent = components[contentlet?.contentType];
    const DefaultComponent = components['CustomNoComponent'] || NoComponent;
    const FallbackComponent = true || isInsideEditor() ? DefaultComponent : EmptyContent;

    const Component = ContentTypeComponent || FallbackComponent;

    return (
        <div
            data-testid="dot-contentlet"
            data-dot-object="contentlet"
            data-dot-identifier={contentlet?.identifier}
            data-dot-basetype={contentlet?.baseType}
            data-dot-title={contentlet?.widgetTitle || contentlet?.title}
            data-dot-inode={contentlet?.inode}
            data-dot-type={contentlet?.contentType}
            data-dot-container={container}
            data-dot-on-number-of-pages={contentlet?.onNumberOfPages}
            key={contentlet?.identifier}
            ref={ref}
            style={{ minHeight: haveContent ? undefined : '4rem' }}>
            <Component {...contentlet} />
        </div>
    );
}

/**
 * Component to render when there is no component for the content type.
 *
 * @param {{ readonly contentType: string }} { contentType }
 * @return {*}
 */
function NoComponent({ contentType }: { readonly contentType: string }) {
    return <div data-testid="no-component">No Component for {contentType}</div>;
}

/**
 * Component to render when there is no content in the container.
 *
 * @return {*}
 */
function EmptyContent() {
    return null;
}

// core-web/libs/sdk/angular/src/lib/layout/container/container.component.ts
import { AsyncPipe, NgComponentOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    Input,
    OnChanges,
    computed,
    inject,
    signal
} from '@angular/core';

import { NoComponentComponent } from '../../components/no-component/no-component.component';
import { DotCMSContainer, DotCMSContentlet, DynamicComponentEntity } from '../../models';
import { PageContextService } from '../../services/dotcms-context/page-context.service';
import { getContainersData } from '../../utils';

interface DotContainer {
    acceptTypes: string;
    identifier: string;
    maxContentlets: number;
    uuid: string;
    variantId?: string;
}

const EMPTY_CONTAINER_EDIT_MODE_STYLES = {
    width: '100%',
    backgroundColor: '#ECF0FD',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#030E32',
    height: '10rem'
};

@Component({
    selector: 'dotcms-container',
    standalone: true,
    imports: [AsyncPipe, NgComponentOutlet, NoComponentComponent],
    templateUrl: './container.component.html',
    styleUrl: './container.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContainerComponent implements OnChanges {
    @Input({ required: true }) container!: DotCMSContainer;

    private readonly pageContextService: PageContextService = inject(PageContextService);
    protected readonly emptyContainerStyles: Record<string, string> =
        EMPTY_CONTAINER_EDIT_MODE_STYLES;
    protected readonly NoComponentComponent = NoComponentComponent;
    protected readonly isInsideEditor = signal<boolean>(false);

    protected componentsMap!: Record<string, DynamicComponentEntity>;
    protected contentlets = signal<DotCMSContentlet[]>([]);
    protected dotContainer = signal<DotContainer | null>(null);
    protected dotContainerAsString = computed(() => JSON.stringify(this.dotContainer()));

    ngOnChanges() {
        const { containers, isInsideEditor } = this.pageContextService.pageContextValue;
        const { acceptTypes, maxContentlets, variantId, path, contentlets } = getContainersData(
            containers,
            this.container
        );
        const { identifier, uuid } = this.container;

        this.componentsMap = this.pageContextService.getComponentMap();

        this.isInsideEditor.set(isInsideEditor);
        this.contentlets.set(contentlets);
        this.dotContainer.set({
            identifier: path ?? identifier,
            acceptTypes,
            maxContentlets,
            variantId,
            uuid
        });
    }
}

@if (isInsideEditor()) {
<div
    [attr.data-dot-accept-types]="dotContainer()?.acceptTypes"
    [attr.data-dot-identifier]="dotContainer()?.identifier"
    [attr.data-max-contentlets]="dotContainer()?.maxContentlets"
    [attr.data-dot-uuid]="dotContainer()?.uuid"
    [style]="contentlets().length ? null : emptyContainerStyles"
    data-testid="dot-container"
    data-dot-object="container">
    @if(contentlets().length){ @for (contentlet of contentlets(); track $index) {
    <div
        [attr.data-dot-identifier]="contentlet.identifier"
        [attr.data-dot-basetype]="contentlet.baseType"
        [attr.data-dot-title]="contentlet['widgetTitle'] || contentlet.title"
        [attr.data-dot-inode]="contentlet.inode"
        [attr.data-dot-type]="contentlet.contentType"
        [attr.data-dot-container]="dotContainerAsString()"
        [attr.data-dot-on-number-of-pages]="contentlet['onNumberOfPages']"
        data-testid="dot-contentlet"
        data-dot-object="contentlet">
        <ng-container
            *ngComponentOutlet="
                (componentsMap[contentlet.contentType] | async) || NoComponentComponent;
                inputs: { contentlet }
            "></ng-container>
    </div>
    } } @else { This container is empty. }
</div>
} @else { @for (contentlet of contentlets(); track $index) {
<ng-container
    *ngComponentOutlet="
        (componentsMap[contentlet.contentType] | async) || NoComponentComponent;
        inputs: { contentlet }
    "></ng-container>
} }
