// core-web/libs/sdk/react/src/lib/components/Container/Container.tsx
import { useContext } from 'react';

import { PageContext } from '../../contexts/PageContext';
import { getContainersData } from '../../utils/utils';
import { PageProviderContext } from '../PageProvider/PageProvider';

const FAKE_CONTENLET = {
    identifier: 'TEMP_EMPTY_CONTENTLET',
    title: 'TEMP_EMPTY_CONTENTLET',
    contentType: 'TEMP_EMPTY_CONTENTLET_TYPE',
    inode: 'TEMPY_EMPTY_CONTENTLET_INODE',
    widgetTitle: 'TEMP_EMPTY_CONTENTLET',
    onNumberOfPages: 1
};

function EmptyContainer() {
    return (
        <div
            data-testid="empty-container"
            style={{
                width: '100%',
                backgroundColor: '#ECF0FD',
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                color: '#030E32',
                height: '10rem'
            }}>
            This container is empty.
        </div>
    );
}

function NoContent({ contentType }: { readonly contentType: string }) {
    return <div data-testid="no-component">No Component for {contentType}</div>;
}

export interface ContainerProps {
    readonly containerRef: PageProviderContext['layout']['body']['rows'][0]['columns'][0]['containers'][0];
}

export function Container({ containerRef }: ContainerProps) {
    const { isInsideEditor } = useContext(PageContext) as PageProviderContext;

    const { identifier, uuid } = containerRef;

    // Get the containers from the global context
    const { containers, components } = useContext<PageProviderContext | null>(
        PageContext
    ) as PageProviderContext;

    const { acceptTypes, contentlets, maxContentlets, variantId, path } = getContainersData(
        containers,
        containerRef
    );

    const updatedContentlets =
        contentlets.length === 0 && isInsideEditor ? [FAKE_CONTENLET] : contentlets;

    const container = {
        acceptTypes,
        identifier: path ?? identifier,
        maxContentlets,
        variantId,
        uuid
    };

    const renderContentlets = updatedContentlets.map((contentlet) => {
        const ContentTypeComponent = components[contentlet.contentType] || NoContent;

        const Component =
            contentlet.identifier === 'TEMP_EMPTY_CONTENTLET'
                ? EmptyContainer
                : ContentTypeComponent;

        return isInsideEditor ? (
            <div
                data-dot-object="contentlet"
                data-dot-identifier={contentlet.identifier}
                data-dot-title={contentlet.widgetTitle || contentlet.title}
                data-dot-inode={contentlet.inode}
                data-dot-type={contentlet.contentType}
                data-dot-container={JSON.stringify(container)}
                key={contentlet.identifier}>
                <Component {...contentlet} />
            </div>
        ) : (
            <Component {...contentlet} key={contentlet.identifier} />
        );
    });

    return isInsideEditor ? (
        <div
            data-dot-object="container"
            data-dot-accept-types={acceptTypes}
            data-dot-identifier={path ?? identifier}
            data-max-contentlets={maxContentlets}
            data-uuid={uuid}>
            {renderContentlets}
        </div>
    ) : (
        // eslint-disable-next-line react/jsx-no-useless-fragment
        <>{renderContentlets}</>
    );
}

// core-web/libs/sdk/angular/src/lib/layout/container/container.component.ts
import { AsyncPipe, NgComponentOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    Input,
    OnChanges,
    computed,
    inject,
    signal
} from '@angular/core';

import { NoComponentComponent } from '../../components/no-component/no-component.component';
import { DotCMSContainer, DotCMSContentlet, DynamicComponentEntity } from '../../models';
import { PageContextService } from '../../services/dotcms-context/page-context.service';
import { getContainersData } from '../../utils';

interface DotContainer {
    acceptTypes: string;
    identifier: string;
    maxContentlets: number;
    uuid: string;
    variantId?: string;
}

const EMPTY_CONTAINER_EDIT_MODE_STYLES = {
    width: '100%',
    backgroundColor: '#ECF0FD',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#030E32',
    height: '10rem'
};

@Component({
    selector: 'dotcms-container',
    standalone: true,
    imports: [AsyncPipe, NgComponentOutlet, NoComponentComponent],
    templateUrl: './container.component.html',
    styleUrl: './container.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContainerComponent implements OnChanges {
    @Input({ required: true }) container!: DotCMSContainer;

    private readonly pageContextService: PageContextService = inject(PageContextService);
    protected readonly emptyContainerStyles: Record<string, string> =
        EMPTY_CONTAINER_EDIT_MODE_STYLES;
    protected readonly NoComponentComponent = NoComponentComponent;
    protected readonly isInsideEditor = signal<boolean>(false);

    protected componentsMap!: Record<string, DynamicComponentEntity>;
    protected contentlets = signal<DotCMSContentlet[]>([]);
    protected dotContainer = signal<DotContainer | null>(null);
    protected dotContainerAsString = computed(() => JSON.stringify(this.dotContainer()));

    ngOnChanges() {
        const { containers, isInsideEditor } = this.pageContextService.pageContextValue;
        const { acceptTypes, maxContentlets, variantId, path, contentlets } = getContainersData(
            containers,
            this.container
        );
        const { identifier, uuid } = this.container;

        this.componentsMap = this.pageContextService.getComponentMap();

        this.isInsideEditor.set(isInsideEditor);
        this.contentlets.set(contentlets);
        this.dotContainer.set({
            identifier: path ?? identifier,
            acceptTypes,
            maxContentlets,
            variantId,
            uuid
        });
    }
}

@if (isInsideEditor()) {
<div
    [attr.data-dot-accept-types]="dotContainer()?.acceptTypes"
    [attr.data-dot-identifier]="dotContainer()?.identifier"
    [attr.data-max-contentlets]="dotContainer()?.maxContentlets"
    [attr.data-dot-uuid]="dotContainer()?.uuid"
    [style]="contentlets().length ? null : emptyContainerStyles"
    data-testid="dot-container"
    data-dot-object="container">
    @if(contentlets().length){ @for (contentlet of contentlets(); track $index) {
    <div
        [attr.data-dot-identifier]="contentlet.identifier"
        [attr.data-dot-basetype]="contentlet.baseType"
        [attr.data-dot-title]="contentlet['widgetTitle'] || contentlet.title"
        [attr.data-dot-inode]="contentlet.inode"
        [attr.data-dot-type]="contentlet.contentType"
        [attr.data-dot-container]="dotContainerAsString()"
        [attr.data-dot-on-number-of-pages]="contentlet['onNumberOfPages']"
        data-testid="dot-contentlet"
        data-dot-object="contentlet">
        <ng-container
            *ngComponentOutlet="
                (componentsMap[contentlet.contentType] | async) || NoComponentComponent;
                inputs: { contentlet }
            "></ng-container>
    </div>
    } } @else { This container is empty. }
</div>
} @else { @for (contentlet of contentlets(); track $index) {
<ng-container
    *ngComponentOutlet="
        (componentsMap[contentlet.contentType] | async) || NoComponentComponent;
        inputs: { contentlet }
    "></ng-container>
} }
