// core-web/libs/sdk/react/src/lib/deprecated/components/BlockEditorRenderer/item/BlockEditorBlock.tsx
import { Blocks, ContentNode } from '@dotcms/uve/internal';

import { CustomRenderer } from '../../../models/content-node.interface';
import { BlockQuote, CodeBlock } from '../blocks/Code';
import { DotContent } from '../blocks/Contentlet';
import { DotCMSImage } from '../blocks/Image';
import { BulletList, ListItem, OrderedList } from '../blocks/Lists';
import { TableRenderer } from '../blocks/Table';
import { Heading, Paragraph, TextBlock } from '../blocks/Texts';
import { DotCMSVideo } from '../blocks/Video';

/**
 * Renders a block editor item based on the provided content and custom renderers.
 *
 * @param content - The content nodes to render.
 * @param customRenderers - Optional custom renderers for specific node types.
 * @returns The rendered block editor item.
 */
export const BlockEditorBlock = ({
    content,
    customRenderers
}: {
    content: ContentNode[];
    customRenderers?: CustomRenderer;
}) => {
    return content?.map((node: ContentNode, index) => {
        const CustomRendererComponent = customRenderers?.[node.type];
        if (CustomRendererComponent) {
            return (
                <CustomRendererComponent
                    key={`${node.type}-${index}`}
                    {...node}
                    content={node.content}>
                    <BlockEditorBlock content={node.content} customRenderers={customRenderers} />
                </CustomRendererComponent>
            );
        }

        switch (node.type) {
            case Blocks.PARAGRAPH:
                return (
                    <Paragraph key={`${node.type}-${index}`} {...node}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </Paragraph>
                );

            case Blocks.HEADING:
                return (
                    <Heading key={`${node.type}-${index}`} {...node}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </Heading>
                );

            case Blocks.TEXT:
                return <TextBlock key={`${node.type}-${index}`} {...node} />;

            case Blocks.BULLET_LIST:
                return (
                    <BulletList key={`${node.type}-${index}`}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </BulletList>
                );

            case Blocks.ORDERED_LIST:
                return (
                    <OrderedList key={`${node.type}-${index}`}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </OrderedList>
                );

            case Blocks.LIST_ITEM:
                return (
                    <ListItem key={`${node.type}-${index}`}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </ListItem>
                );

            case Blocks.BLOCK_QUOTE:
                return (
                    <BlockQuote key={`${node.type}-${index}`}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </BlockQuote>
                );

            case Blocks.CODE_BLOCK:
                return (
                    <CodeBlock key={`${node.type}-${index}`} {...node}>
                        <BlockEditorBlock
                            content={node.content}
                            customRenderers={customRenderers}
                        />
                    </CodeBlock>
                );

            case Blocks.HARDBREAK:
                return <br key={`${node.type}-${index}`} />;

            case Blocks.HORIZONTAL_RULE:
                return <hr key={`${node.type}-${index}`} />;

            case Blocks.DOT_IMAGE:
                return <DotCMSImage key={`${node.type}-${index}`} {...node} />;

            case Blocks.DOT_VIDEO:
                return <DotCMSVideo key={`${node.type}-${index}`} {...node} />;

            case Blocks.TABLE:
                return (
                    <TableRenderer
                        key={`${node.type}-${index}`}
                        content={node.content}
                        blockEditorItem={BlockEditorBlock}
                    />
                );

            case Blocks.DOT_CONTENT:
                return (
                    <DotContent
                        key={`${node.type}-${index}`}
                        {...node}
                        customRenderers={customRenderers}
                    />
                );

            default:
                return <div key={`${node.type}-${index}`}>Unknown Block Type {node.type}</div>;
        }
    });
};

// core-web/libs/sdk/vue/src/lib/components/DotCMSBlockEditorRenderer/components/BlockEditorBlock.vue
<script setup lang="ts">
import type { BlockEditorNode } from '@dotcms/types';
import { BlockEditorDefaultBlocks } from '@dotcms/types/internal';

import BulletList from './blocks/BulletList.vue';
import CodeBlock from './blocks/CodeBlock.vue';
import DotContent from './blocks/DotContent.vue';
import DotImage from './blocks/DotImage.vue';
import DotVideo from './blocks/DotVideo.vue';
import GridBlock from './blocks/GridBlock.vue';
import Heading from './blocks/Heading.vue';
import ListItem from './blocks/ListItem.vue';
import OrderedList from './blocks/OrderedList.vue';
import Paragraph from './blocks/Paragraph.vue';
import Quote from './blocks/Quote.vue';
import TableRenderer from './blocks/TableRenderer.vue';
import TextBlock from './blocks/TextBlock.vue';
import UnknownBlock from './blocks/UnknownBlock.vue';

import type { CustomRenderer } from '../types';

/**
 * Recursive dispatcher: renders a list of block-editor nodes, delegating each to
 * a custom renderer (if provided) or the matching built-in block component.
 */
defineProps<{
    content?: BlockEditorNode[];
    customRenderers?: CustomRenderer;
    isDevMode?: boolean;
}>();

const Blocks = BlockEditorDefaultBlocks;

/** Node types that render their children via a nested dispatcher in the default slot. */
const CONTAINER_BLOCKS: Record<string, unknown> = {
    [Blocks.PARAGRAPH]: Paragraph,
    [Blocks.HEADING]: Heading,
    [Blocks.BULLET_LIST]: BulletList,
    [Blocks.ORDERED_LIST]: OrderedList,
    [Blocks.LIST_ITEM]: ListItem,
    [Blocks.BLOCK_QUOTE]: Quote,
    [Blocks.CODE_BLOCK]: CodeBlock
};

/** Node types that render themselves from attrs with no children slot. */
const LEAF_BLOCKS: Record<string, unknown> = {
    [Blocks.DOT_IMAGE]: DotImage,
    [Blocks.DOT_VIDEO]: DotVideo
};

const containerComponent = (type: string) => CONTAINER_BLOCKS[type];
const leafComponent = (type: string) => LEAF_BLOCKS[type];
</script>

<template>
    <template v-for="(node, index) in content ?? []" :key="`${node.type}-${index}`">
        <!-- Custom renderer takes precedence for any matching block type. -->
        <component
            :is="customRenderers[node.type]"
            v-if="customRenderers && customRenderers[node.type]"
            :node="node">
            <BlockEditorBlock
                :content="node.content"
                :custom-renderers="customRenderers"
                :is-dev-mode="isDevMode" />
        </component>

        <!-- Container blocks: wrap a nested dispatcher of their children. -->
        <component
            :is="containerComponent(node.type)"
            v-else-if="containerComponent(node.type)"
            :node="node">
            <BlockEditorBlock
                :content="node.content"
                :custom-renderers="customRenderers"
                :is-dev-mode="isDevMode" />
        </component>

        <!-- Text leaf: applies marks. -->
        <TextBlock v-else-if="node.type === Blocks.TEXT" :text="node.text" :marks="node.marks" />

        <!-- Attr-driven leaf blocks. -->
        <component
            :is="leafComponent(node.type)"
            v-else-if="leafComponent(node.type)"
            :node="node" />

        <!-- Void blocks. -->
        <br v-else-if="node.type === Blocks.HARDBREAK" />
        <hr v-else-if="node.type === Blocks.HORIZONTAL_RULE" />

        <!-- Complex blocks that recurse internally. -->
        <TableRenderer
            v-else-if="node.type === Blocks.TABLE"
            :content="node.content ?? []"
            :attrs="node.attrs"
            :custom-renderers="customRenderers"
            :is-dev-mode="isDevMode" />
        <GridBlock
            v-else-if="node.type === Blocks.GRID_BLOCK"
            :node="node"
            :custom-renderers="customRenderers"
            :is-dev-mode="isDevMode" />
        <DotContent
            v-else-if="node.type === Blocks.DOT_CONTENT"
            :node="node"
            :custom-renderers="customRenderers"
            :is-dev-mode="isDevMode" />

        <!-- Anything else. -->
        <UnknownBlock v-else :node="node" />
    </template>
</template>
