// examples/astro/src/react/DotCMSPage.tsx
import { DotCMSLayoutBody, useEditableDotCMSPage } from "@dotcms/react/next";

import { pageComponents } from "../components/content-types";

import Footer from "@components/react/Footer";
import Header from "@components/react/Header";

export type MyPageProps = {
  pageResponse: any;
};

export const DotCMSPage = ({ pageResponse }: any) => {
  const { pageAsset, content = {} } = useEditableDotCMSPage<any>(pageResponse);
  const navigation = content.navigation;

  return (
    <div className="flex flex-col min-h-screen gap-6 bg-slate-50">
      {pageAsset?.layout.header && <Header navItems={navigation.children}></Header>}

      <main className="container m-auto">
        <DotCMSLayoutBody page={pageAsset} components={pageComponents} />
      </main>

      {pageAsset?.layout.footer && (
        <Footer {...content} />
      )}
    </div>
  );
};

// examples/angular/src/app/pages/dot-cms-page/dot-cms-page.component.ts
import { Component, inject } from '@angular/core';

import { ErrorComponent } from '../../shared/components/error/error.component';
import { LoadingComponent } from '../../shared/components/loading/loading.component';
import { HeaderComponent } from '../../shared/components/header/header.component';
import { NavigationComponent } from '../../shared/components/navigation/navigation.component';
import { FooterComponent } from '../../shared/components/footer/footer.component';

import { DotCMSLayoutBodyComponent } from '@dotcms/angular';
import { DotCMSPageAsset } from '@dotcms/types';
import { EditablePageService } from '../../services/editable-page.service';
import { DYNAMIC_COMPONENTS } from '../../shared/dynamic-components';
import { buildExtraQuery } from '../../shared/queries';
import { ExtraContent } from '../../shared/contentlet.model';

type DotCMSPage = {
  pageAsset: DotCMSPageAsset;
  content: ExtraContent;
};

@Component({
  selector: 'app-dotcms-page',
  imports: [
    DotCMSLayoutBodyComponent,
    HeaderComponent,
    NavigationComponent,
    FooterComponent,
    ErrorComponent,
    LoadingComponent,
  ],
  providers: [EditablePageService],
  templateUrl: './dot-cms-page.component.html',
})
export class DotCMSPageComponent {
  readonly #editablePageService =
    inject<EditablePageService<DotCMSPage>>(EditablePageService);

  readonly components = DYNAMIC_COMPONENTS;

  $pageState = this.#editablePageService.initializePage({
    graphql: {
      ...buildExtraQuery(),
    },
  });
}

@let pageState = $pageState();

<pre class="whitespace-pre-wrap bg-gray-100 p-4 rounded text-xs">
  {{ pageState.pageResponse?.content | json }}
</pre>

@if (pageState.status !== "idle") {
  <div class="flex flex-col gap-6 min-h-screen bg-neutral-50">
    @if (pageState.pageResponse?.pageAsset?.layout?.header) {
      <app-header>
        @if (pageState.pageResponse?.content?.navigation?.children) {
          <app-navigation
            [items]="
              pageState.pageResponse?.content?.navigation?.children || []
            "
          />
        }
      </app-header>
    }

    <main class="container m-auto">
      @if (pageState.status === "loading") {
        <app-loading />
      } @else if (pageState.status === "error" && pageState.error) {
        <app-error [$error]="pageState.error" />
      } @else if (pageState.status === "success" && pageState.pageResponse) {
        <dotcms-layout-body
          [page]="pageState.pageResponse.pageAsset"
          [components]="components"
        />
      } @else {
        <!-- Add a fallback for unexpected states -->
        <p>Unexpected state encountered.</p>
      }
    </main>

    @if (pageState.pageResponse?.pageAsset?.layout?.footer) {
      <app-footer [content]="pageState.pageResponse?.content" />
    }
  </div>
}
