// core-web/libs/sdk/react/src/lib/components/BlockEditorRenderer/blocks/Image.tsx
import { DotCmsClient } from '@dotcms/client';

import { ContentNode, DotCMSImageProps } from '../../../models/content-node.interface';

/**
 * Renders an image component for dotCMS.
 *
 * @param props - The props for the DotCMSImage component.
 * @returns The rendered image component.
 */
export const DotCMSImage = (props: ContentNode) => {
    const { data, src, alt } = props.attrs as DotCMSImageProps;
    const client = DotCmsClient.instance;

    const srcUrl = data?.identifier ? `${client.dotcmsUrl}${src}` : src;

    return <img alt={alt} src={srcUrl} />;
};

// core-web/libs/sdk/angular/next/components/dotcms-block-editor-renderer/blocks/image.component.ts
import { Component, Input } from '@angular/core';

import { DotCmsClient } from '@dotcms/client';
import { ContentNode } from '@dotcms/uve/internal';

@Component({
    selector: 'dotcms-block-editor-renderer-image',
    standalone: true,
    template: `
        <img [alt]="attrs?.['alt']" [src]="srcUrl" />
    `
})
export class DotCMSBlockEditorRendererImageComponent {
    @Input() attrs!: ContentNode['attrs'];

    private client = DotCmsClient.instance;

    get srcUrl(): string {
        return this.attrs?.['data']?.['identifier']
            ? `${this.client.dotcmsUrl}${this.attrs['src']}`
            : this.attrs?.['src'];
    }
}
