// examples/vuejs/src/components/editor/EditButton.vue
<script setup lang="ts">
import type { DotCMSBasicContentlet } from '@dotcms/types';
import { editContentlet } from '@dotcms/uve';

import { useIsEditMode } from '@/composables/useIsEditMode';

/** Opens the contentlet editor in the UVE. Only visible in edit mode. */
const props = defineProps<{ contentlet: Partial<DotCMSBasicContentlet> }>();

const isEditMode = useIsEditMode();

const onEdit = (event: MouseEvent) => {
    event.stopPropagation();
    editContentlet(props.contentlet as DotCMSBasicContentlet);
};
</script>

<template>
    <button
        v-if="isEditMode"
        type="button"
        class="absolute right-2 top-2 z-20 rounded-full bg-primary px-3 py-1 text-xs font-semibold text-bg shadow-md transition-colors hover:bg-primary-deep"
        @click="onEdit">
        Edit
    </button>
</template>

// examples/astro/src/components/ui/EditButton.tsx
import type { DotCMSBasicContentlet } from '@dotcms/types';
import { editContentlet } from '@dotcms/uve';
import { useIsEditMode } from '@/hooks';

export function EditButton({ contentlet }: { contentlet: DotCMSBasicContentlet }) {
    const isEditMode = useIsEditMode();
    return (
        isEditMode && (
            <button
                onClick={() => editContentlet(contentlet)}
                className="absolute bottom-2 right-2 z-10 bg-blue-500 cursor-pointer text-white rounded-md py-1 px-3 text-sm shadow-md hover:bg-blue-600">
                Edit
            </button>
        )
    );
}
