// examples/astro/src/react/shared/contentlet.tsx
import { useMemo, type FC } from "react";
import { isInsideEditor } from "@dotcms/client";
import type { DotCMSContentlet } from "@dotcms/types";

export type ContentletProps = {
  contentlet: DotCMSContentlet;
  children: React.ReactNode;
};

export const Contentlet: FC<ContentletProps> = ({ contentlet, children }) => {
  const insideEditor = useMemo(isInsideEditor, []);

  return insideEditor ? (
    <div
      data-dot-object="contentlet"
      data-dot-identifier={contentlet.identifier}
      data-dot-basetype={contentlet.baseType}
      data-dot-title={contentlet.widgetTitle || contentlet.title}
      data-dot-inode={contentlet.inode}
      data-dot-type={contentlet.contentType}
      data-dot-on-number-of-pages={contentlet.onNumberOfPages ?? 0}
      key={contentlet.identifier}
    >
      {children}
    </div>
  ) : (
    children
  );
};

export default Contentlet;

// examples/angular/src/app/shared/contentlet/contentlet.component.ts
import { Component, input } from '@angular/core';

import { GenericContentlet } from '../../pages/components';
import { Contentlet } from '@dotcms/client/src/lib/client/content/shared/types';
import { isInsideEditor } from '@dotcms/client';
import { NgTemplateOutlet } from '@angular/common';

/**
 * Local component for rendering a contentlet outside the DotCmsLayout.
 */
@Component({
  selector: 'app-contentlet',
  standalone: true,
  imports: [NgTemplateOutlet],
  template: `
    @if(isInsideEditor) {
    <div
      data-dot-object="contentlet"
      [attr.data-dot-identifier]="contentlet().identifier"
      [attr.data-dot-basetype]="contentlet().baseType"
      [attr.data-dot-title]="contentlet().widgetTitle || contentlet().title"
      [attr.data-dot-inode]="contentlet().inode"
      [attr.data-dot-type]="contentlet().contentType"
      [attr.data-dot-on-number-of-pages]="contentlet().onNumberOfPages ?? 0"
    >
      <ng-container *ngTemplateOutlet="contentletTemplate"></ng-container>
    </div>

    } @else {
    <ng-container *ngTemplateOutlet="contentletTemplate"></ng-container>
    }

    <ng-template #contentletTemplate> <ng-content /></ng-template>
  `,
})
export class ContentletComponent {
  contentlet = input.required<Contentlet<GenericContentlet>>();

  protected readonly isInsideEditor = isInsideEditor();
}
