// examples/astro/src/components/content-types/Banner.tsx
import { DotCMSEditableText } from "@dotcms/react/next";
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface BannerProps extends DotCMSBasicContentlet {
  caption: string;
  inode: string;
  image: string;
  link: string;
  buttonText: string;
}

function Banner(contentlet: BannerProps) {
  const { title, caption, inode, image, link, buttonText } = contentlet;

  return (
    <div className="relative bg-gray-200 h-96 mb-4">
      {image && (
        <img src={`/dA/${inode}`} className="w-full h-full object-cover" alt={title} />
      )}
      <div className="absolute inset-0 flex flex-col items-center justify-center p-4 text-center text-white">
        <h2 className="mb-2 text-6xl font-bold text-shadow">
          <DotCMSEditableText contentlet={contentlet} fieldName="title" />
        </h2>
        <p className="mb-4 text-xl text-shadow">{caption}</p>
        {link && (
          <a
            className="p-4 text-xl transition duration-300 bg-blue-500 rounded-sm hover:bg-blue-700"
            href={link}
          >
            {buttonText || "See more"}
          </a>
        )}
      </div>
    </div>
  );
}

export default Banner;

// examples/angular/src/app/content-types/banner/banner.component.ts
import { NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { DotCMSEditableTextComponent } from '@dotcms/angular/next';
import { DotCMSBasicContentlet } from '@dotcms/types';

interface BannerContentlet extends DotCMSBasicContentlet {
    image: {
        identifier: string;
    };
    title: string;
    caption: string;
    link: string;
    buttonText: string;
}

@Component({
    selector: 'app-banner',
    standalone: true,
    imports: [RouterLink, NgOptimizedImage, DotCMSEditableTextComponent],
    template: `<div
        class="flex overflow-hidden relative justify-center items-center w-full h-96 bg-gray-200">
        @if (contentlet().image; as image) {
        <img
            class="object-cover w-full"
            [ngSrc]="image.identifier"
            [alt]="contentlet().title"
            fill
            priority />
        }
        <div
            class="flex absolute inset-0 flex-col justify-center items-center p-4 text-center text-white">
            <h2 class="mb-2 text-6xl font-bold text-shadow">
                <dotcms-editable-text fieldName="title" [contentlet]="contentlet()" />
            </h2>
            <p class="mb-4 text-xl text-shadow">{{ contentlet().caption }}</p>
            <a
                class="p-4 text-xl bg-red-400 rounded transition duration-300 hover:bg-red-500"
                [routerLink]="contentlet().link">
                {{ contentlet().buttonText }}
            </a>
        </div>
    </div>`,
    styleUrl: './banner.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class BannerComponent {
    contentlet = input.required<BannerContentlet>();
}
