// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/container/components/container-not-found/container-not-found.component.ts
import { NgStyle } from '@angular/common';
import { Component, inject, Input, OnInit } from '@angular/core';

import { EMPTY_CONTAINER_STYLE_ANGULAR } from '@dotcms/uve/internal';

import { DotCMSStore } from '../../../../../../store/dotcms.store';

@Component({
    selector: 'dotcms-container-not-found',
    standalone: true,
    imports: [NgStyle],
    template: `
        @if ($isDevMode()) {
            <div [attr.data-testid]="'container-not-found'" [ngStyle]="emptyContainerStyle">
                This container with identifier {{ identifier }} was not found.
            </div>
        }
    `
})
export class ContainerNotFoundComponent implements OnInit {
    @Input() identifier = 'unknown';

    #dotcmsContextService = inject(DotCMSStore);

    $isDevMode = this.#dotcmsContextService.$isDevMode;
    emptyContainerStyle = EMPTY_CONTAINER_STYLE_ANGULAR;

    ngOnInit() {
        if (this.$isDevMode()) {
            console.error(`Container with identifier ${this.identifier} not found`);
        }
    }
}

// core-web/libs/sdk/vue/src/lib/components/Container/ContainerNotFound.vue
<script setup lang="ts">
import { onMounted } from 'vue';

import { EMPTY_CONTAINER_STYLE_REACT } from '@dotcms/uve/internal';

import { useIsDevMode } from '../../composables/useIsDevMode';

/** @internal Dev-only message shown when a container cannot be found on the page. */
const props = defineProps<{ identifier: string }>();

const isDevMode = useIsDevMode();

onMounted(() => {
    if (isDevMode.value) {
        console.error(`Container with identifier ${props.identifier} not found`);
    }
});
</script>

<template>
  <div
    v-if="isDevMode"
    data-testid="container-not-found"
    :style="EMPTY_CONTAINER_STYLE_REACT"
  >
    This container with identifier {{ identifier }} was not found.
  </div>
</template>
