// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/container/components/empty-container/empty-container.component.ts
import { NgStyle } from '@angular/common';
import { Component, inject } from '@angular/core';

import { EMPTY_CONTAINER_STYLE_ANGULAR } from '@dotcms/uve/internal';

import { DotCMSStore } from '../../../../../../store/dotcms.store';

/**
 * @description This component is used to display a message when a container is empty.
 * @export
 * @internal
 * @class EmptyContainerComponent
 */
@Component({
    selector: 'dotcms-empty-container',
    standalone: true,
    imports: [NgStyle],
    template: `
        @if ($isDevMode()) {
            <div [ngStyle]="emptyContainerStyle" data-testid="empty-container">
                <span data-testid="empty-container-message" data-dot-object="empty-content">
                    This container is empty.
                </span>
            </div>
        }
    `
})
export class EmptyContainerComponent {
    emptyContainerStyle = EMPTY_CONTAINER_STYLE_ANGULAR;

    #dotCMSStore = inject(DotCMSStore);

    $isDevMode = this.#dotCMSStore.$isDevMode;
}

// core-web/libs/sdk/vue/src/lib/components/Container/EmptyContainer.vue
<script setup lang="ts">
import { EMPTY_CONTAINER_STYLE_REACT } from '@dotcms/uve/internal';

import { useIsDevMode } from '../../composables/useIsDevMode';

/**
 * @internal
 * Dev-only placeholder for an empty container. The container's `data-dot-*`
 * attributes are forwarded via fallthrough attrs so the editor can target it.
 */
defineOptions({ inheritAttrs: false });

const isDevMode = useIsDevMode();
</script>

<template>
  <div
    v-if="isDevMode"
    v-bind="$attrs"
    :style="EMPTY_CONTAINER_STYLE_REACT"
  >
    <span
      data-testid="empty-container-message"
      data-dot-object="empty-content"
    >
      This container is empty.
    </span>
  </div>
</template>
