// examples/astro/src/react/shared/contentlets.tsx
import useImageSrc from "../hooks/useImageSrc";
import Contentlet from "./contentlet";

const dateFormatOptions: DateTimeFormatOptions = {
    year: "numeric",
    month: "long",
    day: "numeric",
};

function Contentlets({ contentlets }) {
    return (
        <ul className="flex flex-col gap-7">
            {contentlets.map((contentlet) => (
                <Contentlet contentlet={contentlet} key={contentlet.identifier}>
                    <li className="flex gap-7 min-h-16">
                        <a
                            className="relative min-w-32"
                            href={contentlet.urlMap || contentlet.url}
                        >
                            {contentlet.image && (
                                <img
                                    src={
                                        useImageSrc({
                                            src: contentlet.image?.idPath ?? contentlet.image
                                        })
                                    }
                                    alt={contentlet.urlTitle}
                                    className="object-cover absolute w-full h-full top-0 left-0"
                                />
                            )}
                        </a>
                        <div className="flex flex-col gap-1">
                            <a
                                className="text-sm text-zinc-900 font-bold"
                                href={contentlet.urlMap || contentlet.url}
                            >
                                {contentlet.title}
                            </a>
                            <time className="text-zinc-600">
                                {new Date(
                                    contentlet.modDate
                                ).toLocaleDateString(
                                    "en-US",
                                    dateFormatOptions
                                )}
                            </time>
                        </div>
                    </li>
                </Contentlet>
            ))}
        </ul>
    );
}

export default Contentlets;

// examples/angular/src/app/shared/contentlets-wrapper/contentlets.component.ts
import { Component, input } from '@angular/core';

import { DatePipe, NgOptimizedImage } from '@angular/common';
import { ContentletComponent } from './contentlet/contentlet.component';
import { Contentlet } from '../models';

/**
 * Local component for rendering a list of contentlets outside the DotCmsLayout.
 *
 * @export
 * @class ContentletsComponent
 */
@Component({
    selector: 'app-contentlets-wrapper',
    standalone: true,
    imports: [NgOptimizedImage, DatePipe, ContentletComponent],
    template: `<ul class="flex flex-col gap-7">
        @for (contentlet of contentlets(); track contentlet.identifier) {
        <app-contentlet [contentlet]="contentlet">
            <li class="flex gap-7 min-h-16">
                <a class="relative min-w-32" [href]="contentlet.urlMap ?? contentlet.url">
                    <img
                        [ngSrc]="contentlet.image.identifier"
                        [fill]="true"
                        [alt]="contentlet.urlTitle ?? contentlet.title"
                        [loaderParams]="{ languageId: contentlet.languageId || 1 }"
                        class="object-cover" />
                </a>
                <div class="flex flex-col gap-1">
                    <a
                        class="text-sm font-bold text-zinc-900"
                        [href]="contentlet.urlMap ?? contentlet.url">
                        {{ contentlet.title }}
                    </a>
                    <time class="text-zinc-600">
                        {{ contentlet.modDate | date : 'mediumDate' }}
                    </time>
                </div>
            </li>
        </app-contentlet>
        }
    </ul> `
})
export class ContentletsWrapperComponent {
    contentlets = input.required<Contentlet[]>();
}
