// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/dotcms-block-editor-renderer.component.ts
import { Component, Input, signal } from '@angular/core';

import { UVE_MODE, BlockEditorNode } from '@dotcms/types';
import { BlockEditorState } from '@dotcms/types/internal';
import { getUVEState } from '@dotcms/uve';
import { isValidBlocks } from '@dotcms/uve/internal';

import { DotCMSBlockEditorItemComponent } from './item/dotcms-block-editor-item.component';

import { DynamicComponentEntity } from '../../models';

/**
 * Represents a Custom Renderer used by the Block Editor Component
 *
 * @export
 * @interface CustomRenderer
 */
export type CustomRenderer = Record<string, DynamicComponentEntity>;

/**
 * A component that renders content from DotCMS's Block Editor field.
 *
 * This component provides an easy way to render Block Editor content in your Angular applications.
 * It handles the rendering of standard blocks and allows customization through custom renderers.
 *
 * For more information about Block Editor, see {@link https://dev.dotcms.com/docs/block-editor}
 *
 * @example
 * ```html
 * <dotcms-block-editor-renderer
 *   [blocks]="myBlockEditorContent"
 *   [customRenderers]="myCustomRenderers">
 * </dotcms-block-editor-renderer>
 * ```
 */
@Component({
    selector: 'dotcms-block-editor-renderer',
    templateUrl: './dotcms-block-editor-renderer.component.html',
    styleUrls: ['./dotcms-block-editor-renderer.component.scss'],
    imports: [DotCMSBlockEditorItemComponent]
})
export class DotCMSBlockEditorRendererComponent {
    @Input() blocks!: BlockEditorNode;
    @Input() customRenderers: CustomRenderer | undefined;
    @Input() class: string | undefined;
    @Input() style: string | Record<string, string> | undefined;

    $blockEditorState = signal<BlockEditorState>({ error: null });
    $isInEditMode = signal(getUVEState()?.mode === UVE_MODE.EDIT);

    ngOnInit() {
        const state = isValidBlocks(this.blocks);

        if (state.error) {
            console.error('Error in dotcms-block-editor-renderer: ', state.error);
        }

        this.$blockEditorState.set(isValidBlocks(this.blocks));
    }
}

@if ($blockEditorState().error && $isInEditMode()) {
    <div data-testid="invalid-blocks-message">
        {{ $blockEditorState().error }}
    </div>
} @else if (!$blockEditorState().error) {
    <div [class]="class()" [style]="style()">
        <dotcms-block-editor-renderer-block
            [content]="blocks()?.content"
            [customRenderers]="customRenderers()" />
    </div>
}

// core-web/libs/sdk/vue/src/lib/components/DotCMSBlockEditorRenderer/DotCMSBlockEditorRenderer.vue
<script setup lang="ts">
import { computed, withDefaults } from 'vue';

import { isValidBlocks } from '@dotcms/uve/internal';

import BlockEditorBlock from './components/BlockEditorBlock.vue';
import type { BlockEditorRendererProps } from './types';

/**
 * Renders a dotCMS Block Editor field.
 *
 * @example
 * ```vue
 * <DotCMSBlockEditorRenderer :blocks="contentlet.body" :custom-renderers="renderers" />
 * ```
 */
const props = withDefaults(defineProps<BlockEditorRendererProps>(), {
    isDevMode: false
});

const validation = computed(() => isValidBlocks(props.blocks));
const errorMessage = computed(() => {
    const error = validation.value.error;

    if (error) {
        console.error(error);
    }

    return error;
});
</script>

<template>
  <div
    v-if="errorMessage && isDevMode"
    data-testid="invalid-blocks-message"
  >
    {{ errorMessage }}
  </div>
  <div
    v-else-if="!errorMessage"
    :class="className"
    :style="style"
    data-testid="dot-block-editor-container"
  >
    <BlockEditorBlock
      :content="blocks?.content"
      :custom-renderers="customRenderers"
      :is-dev-mode="isDevMode"
    />
  </div>
</template>
