// examples/astro/src/components/content-types/PageForm.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";
import { useIsEditMode } from "@/hooks";

import { ContactUs } from "@/components/ui";

interface PageFormProps extends DotCMSBasicContentlet {
  formType: string;
  description: string;
}

export default function PageForm(contentlet: PageFormProps) {
  const { formType } = contentlet;
  const isEditMode = useIsEditMode();

  if (formType === "contact-us") {
    return <ContactUs {...contentlet} />;
  }

  if (isEditMode) {
    return (
      <div>
        <h4>There is no form component for this form type: {formType}</h4>
      </div>
    );
  }

  return null;
}

// core-web/app/ng-ssr/src/app/dotcms/components/page-form/page-form.component.ts
import { Component, computed, input } from '@angular/core';

import { DotCMSShowWhenDirective } from '@dotcms/angular';
import { UVE_MODE } from '@dotcms/types';

import { ContactUsComponent } from './components/contact-us/contact-us.component';

import { PageForm } from '../../types/contentlet.model';

@Component({
  selector: 'app-page-form',
  imports: [DotCMSShowWhenDirective, ContactUsComponent],
  template: `
    @if (formType() === 'contact-us') {
      <app-contact-us [description]="description()" />
    } @else {
      <ng-container [dotCMSShowWhen]="UVE_MODE.EDIT">
        <div>
          <h4>
            There is no form component for this form type: {{ formType() }}
          </h4>
        </div>
      </ng-container>
    }
  `,
})
export class PageFormComponent {
  contentlet = input.required<PageForm>();

  formType = computed(() => this.contentlet().formType);
  description = computed(() => this.contentlet().description || '');
  UVE_MODE = UVE_MODE;
}
