// examples/astro/src/react/layout/navigation.tsx
function Navigation({
  items,
  className,
}: {
  items?: any[];
  className?: string;
}) {
  return (
    <nav className={className}>
      <ul className="flex space-x-4 text-white">
        <li>
          <a href="/">
            {" "}
            {/* I NEED TO PRESERVE THE QUERY PARAMS*/}
            Home
          </a>
        </li>
        {items?.map((item) => (
          <li key={item.folder}>
            <a
              href={item.href} // I NEED TO PRESERVE THE QUERY PARAMS
              target={item.target}
            >
              {item.title}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

export default Navigation;

// ema/vuejs/src/components/Navigation.vue
<template>
  <ul class="flex space-x-4 text-white">
    <li v-for="item in nav" :key="item.href">
      <RouterLink :to="item.href">{{ item.title }}</RouterLink>
    </li>
  </ul>
</template>

<script setup>
import { defineProps } from 'vue'
import { RouterLink } from 'vue-router'

defineProps({
  nav: {
    type: Array,
    required: true
  }
})
</script>
