// core-web/libs/sdk/react/src/lib/components/Row/Row.tsx
import { forwardRef } from 'react';

import styles from './row.module.css';

import { Column } from '../Column/Column';
import { PageProviderContext } from '../PageProvider/PageProvider';

/**
 * Props for the row component
 *
 * @interface RowProps
 *
 */
export interface RowProps {
    /**
     * Row data
     *
     * @type {PageProviderContext['layout']['body']['rows'][0]}
     * @memberof RowProps
     */
    row: PageProviderContext['layout']['body']['rows'][0];
}

/**
 * Renders a row
 *
 * @category Components
 * @param {React.ForwardedRef<HTMLDivElement, RowProps>} ref
 * @return {*}
 */
export const Row = forwardRef<HTMLDivElement, RowProps>((props: RowProps, ref) => {
    const { row } = props;

    return (
        <div
            data-testid="row"
            data-dot="row"
            ref={ref}
            className={`${styles.row} ${row.styleClass}`}>
            {row.columns.map((column, index) => (
                <Column key={index} column={column} />
            ))}
        </div>
    );
});

// ema/vuejs/src/components/Row.vue
<script>
import { computed } from 'vue'
import Column from './Column.vue' // Adjust the import path as necessary

export default {
  components: {
    Column
  },
  props: {
    row: Object
  },
  setup(props) {
    const combinedClasses = computed(() => {
      return [props.row.styleClass].filter(Boolean).join(' ')
    })

    const rowProps = {
      'data-dot': 'row',
      'data-testid': 'row'
    }

    return { combinedClasses, rowProps }
  }
}
</script>

<template>
  <div class="row" v-bind="rowProps">
    <Column v-for="(column, index) in row.columns" :key="index" :column="column" />
  </div>
</template>

<style>
.row {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
  gap: 1rem;
}
</style>
