// libs/dotcms-webcomponents/src/elements/dot-contentlet-thumbnail/dot-contentlet-thumbnail.tsx
import { Component, h, Host, Prop, State } from '@stencil/core';
import { DotContentletItem } from '../../models/dot-contentlet-item.model';

@Component({
    tag: 'dot-contentlet-thumbnail',
    styleUrl: 'dot-contentlet-thumbnail.scss'
})
export class DotContentletThumbnail {
    @Prop({ reflect: true })
    height = '';

    @Prop({ reflect: true })
    width = '';

    @Prop({ reflect: true })
    alt = '';

    @Prop({ reflect: true })
    iconSize = '';

    @Prop()
    contentlet: DotContentletItem;

    @State() renderImage: boolean;

    componentWillLoad() {
        this.renderImage =
            this.contentlet?.hasTitleImage === 'true' ||
            this.contentlet?.mimeType === 'application/pdf';
    }

    render() {
        const image = this.contentlet ? `url(${this.getImageURL()})` : '';

        return (
            <Host>
                {this.renderImage ? (
                    <div class="thumbnail" style={{ 'background-image': image }}>
                        <img
                            src={this.getImageURL()}
                            alt={this.alt}
                            aria-label={this.alt}
                            onError={() => {
                                this.switchToIcon();
                            }}
                        />
                    </div>
                ) : (
                    <dot-contentlet-icon
                        icon={this.contentlet?.baseType !== 'FILEASSET' ? this.contentlet?.contentTypeIcon : this.contentlet?.__icon__}
                        size={this.iconSize}
                        aria-label={this.alt}
                    />
                )}
            </Host>
        );
    }

    private getImageURL(): string {
        return this.contentlet.mimeType === 'application/pdf'
            ? `/contentAsset/image/${this.contentlet.inode}/${this.contentlet.titleImage}/pdf_page/1/resize_w/250/quality_q/45`
            : `/dA/${this.contentlet.inode}/500w/20q`;
    }

    private switchToIcon(): any {
        this.renderImage = false;
    }
}

// core-web/libs/ui/src/lib/components/dot-contentlet-thumbnail.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

import { DotCMSContentlet } from '@dotcms/dotcms-models';

@Component({
    selector: 'dot-contentlet-thumbnail',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './dot-contentlet-thumbnail.component.html',
    styleUrl: './dot-contentlet-thumbnail.component.scss',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DotContentletThumbnailComponent {
    @Input() contentlet: DotCMSContentlet;
    @Input() size = 64;
    @Input() showLabel = true;

    /**
     * Get thumbnail URL for the contentlet
     */
    getThumbnailUrl(): string {
        if (!this.contentlet) {
            return '';
        }

        // Handle PDF files
        if (this.contentlet.mimeType === 'application/pdf') {
            return `/contentAsset/image/${this.contentlet.inode}/${
                this.contentlet.titleImage
            }/pdf_page/1/resize_w/250/quality_q/45`;
        }

        // Handle SVG files
        if (this.contentlet.mimeType === 'image/svg+xml') {
            return `/contentAsset/image/${this.contentlet.inode}/asset`;
        }

        // Handle regular images with dA path
        if (this.contentlet.titleImage && this.contentlet.titleImage.length) {
            const timestamp = this.contentlet.modDate || '';

            return `/dA/${this.contentlet.inode}/${this.contentlet.titleImage}/500w/50q?r=${timestamp}`;
        }

        // Fallback to icons
        if (this.contentlet.__icon__) {
            return this.contentlet.__icon__;
        }

        return this.contentlet.contentTypeIcon || '';
    }

    /**
     * Get title for the contentlet
     */
    getTitle(): string {
        return this.contentlet?.title || '';
    }
}

<div class="dot-contentlet-thumbnail">
    <div class="dot-contentlet-thumbnail__image" [style.width.px]="size" [style.height.px]="size">
        <img *ngIf="getThumbnailUrl()" [src]="getThumbnailUrl()" [alt]="getTitle()" />
    </div>
    <div *ngIf="showLabel && getTitle()" class="dot-contentlet-thumbnail__label">
        {{ getTitle() }}
    </div>
</div>
