// examples/astro/src/react/layout/footer/Footer.tsx
import Blogs from "./components/blogs";
import Destinations from "./components/destinations";

function Footer({ blogs, destinations }: { blogs: any, destinations: any }) {
    return (
        <footer className="p-4 bg-slate-600 text-white py-24">
            <div className="grid md:grid-cols-3 sm:grid-cols-1 md:grid-rows-1 sm:grid-rows-3 gap-7 mx-24">
                <div className="flex flex-col gap-7">
                    <h2 className="text-2xl font-bold text-white">About us</h2>
                    <p className="text-sm text-white">
                        We are TravelLux, a community of dedicated travel
                        experts, journalists, and bloggers. Our aim is to offer
                        you the best insight on where to go for your travel as
                        well as to give you amazing opportunities with free
                        benefits and bonuses for registered clients.
                    </p>
                </div>

                <Blogs blogs={blogs} />
                <Destinations destinations={destinations} />
            </div>
        </footer>
    );
}

export default Footer;

// examples/angular/src/app/pages/components/footer/footer.component.ts
import { environment } from '../../../../environments/environment';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

import { BlogsComponent } from '../../../components/blogs/blogs.component';
import { DestinationsComponent } from '../../../components/destinations/destinations.component';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [BlogsComponent, DestinationsComponent, NgOptimizedImage],
  template: `<footer class="p-4 text-white bg-red-100 py-24">
    <div
      class="grid md:grid-cols-3 sm:grid-cols-1 md:grid-rows-1 sm:grid-rows-3 gap-7 mx-24"
    >
      <div class="flex gap-7 flex-col">
        <h2 class="text-2xl font-bold text-black">About us</h2>
        <p class="text-sm text-zinc-800">
          We are TravelLux, a community of dedicated travel experts,
          journalists, and bloggers. Our aim is to offer you the best insight on
          where to go for your travel as well as to give you amazing
          opportunities with free benefits and bonuses for registered clients.
        </p>
        <img
          ngSrc="/dA/82da90eb04/fileAsset/logo.png"
          height="53"
          width="221"
          alt="TravelLux logo"
        />
      </div>
      <app-blogs />
      <app-destinations />
    </div>
  </footer>`,
  styleUrl: './footer.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooterComponent {
  protected readonly environment = environment;
}
