// core-web/libs/sdk/angular/src/lib/components/dotcms-layout-body/components/column/column.component.ts
import { ChangeDetectionStrategy, Component, HostBinding, OnChanges, input } from '@angular/core';

import { DotPageAssetLayoutColumn } from '@dotcms/types';
import { combineClasses, getColumnPositionClasses } from '@dotcms/uve/internal';

import { ContainerComponent } from '../container/container.component';
/**
 * This component renders a column with all its content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @internal
 */
@Component({
    selector: 'dotcms-column',
    imports: [ContainerComponent],
    template: `
        <div [class]="column().styleClass" data-testid="dotcms-column">
            @for (container of column().containers; track $index) {
                <dotcms-container [container]="container" />
            }
        </div>
    `,
    styleUrl: './column.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ColumnComponent implements OnChanges {
    /**
     * The column data to be rendered
     */
    readonly column = input.required<DotPageAssetLayoutColumn>();

    @HostBinding('class') customClasses = '';

    ngOnChanges() {
        const positionClasses = getColumnPositionClasses(this.column());

        this.customClasses = combineClasses([positionClasses.startClass, positionClasses.endClass]);
    }
}

// core-web/libs/sdk/react/src/lib/next/components/Column/Column.tsx
import styles from './Column.module.css';

import { isInsideEditor } from '@dotcms/client';

import { combineClasses, getPositionStyleClasses } from '../../utils';
import { Container } from '../Container/Container';
import { DotPageAssetLayoutColumn } from '../../types';

/**
 * Props for Column component to render a column with its containers.
 *
 * @export
 * @interface ColumnProps
 */
export interface ColumnProps {
    readonly column: DotPageAssetLayoutColumn;
}

/**
 * Renders a Column with its containers using information provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @export
 * @param {ColumnProps} { column }
 * @return {JSX.Element} Rendered column with containers
 */
export function Column({ column }: ColumnProps) {
    const { startClass, endClass } = getPositionStyleClasses(
        column.leftOffset,
        column.width + column.leftOffset
    );
    const combinedClasses = combineClasses([styles[endClass], styles[startClass]]);
    const columnProps = { 'data-dot': 'column' };

    return (
        <div {...columnProps} className={combinedClasses}>
            <div className={column.styleClass}>
                {column.containers.map((container) => (
                    <Container
                        key={`${container.identifier}-${container.uuid}`}
                        container={container}
                    />
                ))}
            </div>
        </div>
    );
}
