// core-web/libs/sdk/react/src/lib/next/components/DotCMSLayoutBody/components/ErrorMessage.tsx
import { useEffect } from 'react';

import { DotCMSPageRendererMode } from '@dotcms/uve/types';

import { useIsDevMode } from '../../../hooks/useIsDevMode';

/**
 * Error message component for when the page body is missing
 *
 * @return {JSX.Element} Error message component
 */
export const ErrorMessage = ({ mode }: { mode: DotCMSPageRendererMode }) => {
    useEffect(() => {
        console.warn('Missing required layout.body property in page');
    }, []);

    const isDevMode = useIsDevMode(mode);

    if (!isDevMode) {
        return null;
    }

    return (
        <div
            data-testid="error-message"
            style={{ padding: '1rem', border: '1px solid #e0e0e0', borderRadius: '4px' }}>
            <p style={{ margin: '0 0 0.5rem', color: '#666' }}>
                The <code>page</code> is missing the required <code>layout.body</code> property.
            </p>
            <p style={{ margin: 0, color: '#666' }}>
                Make sure the page asset is properly loaded and includes a layout configuration.
            </p>
        </div>
    );
};

// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/error-message/error-message.component.ts
import { ChangeDetectionStrategy, Component, inject, Input, OnInit, signal } from '@angular/core';

import { DotCMSPageRendererMode, UVE_MODE } from '@dotcms/uve/types';
import { DotCMSContextService } from 'libs/sdk/angular/next/services/dotcms-context/dotcms-context.service';

/**
 *
 * `ErrorMessageComponent` is a class that represents the error message for a DotCMS page.
 *
 * @internal
 * @class ErrorMessageComponent
 */
@Component({
    selector: 'error-message',
    standalone: true,
    imports: [],
    template: `
        @if (isDevMode()) {
            <div
                data-testid="error-message"
                style="padding: 1rem; border: 1px solid #e0e0e0; border-radius: 4px;">
                <p style="margin: 0 0 0.5rem; color: #666;">
                    The
                    <code>page</code>
                    is missing the required
                    <code>layout.body</code>
                    property.
                </p>
                <p style="margin: 0; color: #666;">
                    Make sure the page asset is properly loaded and includes a layout configuration.
                </p>
            </div>
        }
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ErrorMessageComponent implements OnInit {
    @Input() mode: DotCMSPageRendererMode = 'production';

    private dotCMSContextService = inject(DotCMSContextService);

    isDevMode = signal(false);

    ngOnInit(): void {
        console.warn('Missing required layout.body property in page');

        const isDevMode = this.dotCMSContextService.isDevMode(this.mode);

        this.isDevMode.set(isDevMode);
    }
}
