// examples/astro/src/components/ui/RecommendedCard.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface RecommendedCardProps extends DotCMSBasicContentlet {
  urlMap: string;
}

const dateFormatOptions: Intl.DateTimeFormatOptions = {
  year: "numeric",
  month: "long",
  day: "numeric",
};

export const RecommendedCard = ({
  contentlet,
}: {
  contentlet: RecommendedCardProps;
}) => {
  const { url, title, inode, image, urlMap, modDate } = contentlet;

  return (
    <div className="flex gap-7 relative">
      {/* <EditButton contentlet={contentlet} /> */}
      <a className="relative min-w-32" href={urlMap || url}>
        {image && (
          <img
            src={`/dA/${inode}/250w`}
            alt={title}
            className="object-cover w-[128px] h-[88px]"
          />
        )}
      </a>
      <div className="flex flex-col gap-1">
        <a className="text-sm text-white font-bold" href={urlMap || url}>
          {title}
        </a>
        <time className="text-gray-400">
          {new Date(modDate).toLocaleDateString("en-US", dateFormatOptions)}
        </time>
      </div>
    </div>
  );
};

// examples/angular-ssr/src/app/components/footer/components/recommended-card/recommended-card.component.ts
import { Component, input } from '@angular/core';

import { DatePipe, NgOptimizedImage } from '@angular/common';

import { editContentlet } from '@dotcms/uve';
import { UVE_MODE } from '@dotcms/types';
import { EditContentletButtonComponent } from '../../../edit-contentlet-button/edit-contentlet-button.component';
import { Contentlet } from '../../../../dotcms/types/contentlet.model';

/**
 * Local component for rendering a recommended card.
 *
 * @export
 * @class RecommendedCardComponent
 */
@Component({
  selector: 'app-recommended-card',
  imports: [NgOptimizedImage, DatePipe, EditContentletButtonComponent],
  template: `
    <div class="flex gap-7 min-h-16 relative">
      <app-edit-contentlet-button [contentlet]="contentlet()" />
      <a
        class="relative min-w-32"
        [href]="contentlet().urlMap ?? contentlet().url"
      >
        <img
          [ngSrc]="contentlet().image.fileAsset.versionPath"
          [fill]="true"
          [alt]="contentlet().urlTitle ?? contentlet().title"
          [loaderParams]="{ languageId: contentlet().languageId || 1 }"
          class="object-cover"
        />
      </a>
      <div class="flex flex-col gap-1">
        <a
          class="text-sm font-bold text-zinc-900"
          [href]="contentlet().urlMap ?? contentlet().url"
        >
          {{ contentlet().title }}
        </a>
        <time class="text-zinc-600">
          {{ contentlet().modDate | date: 'mediumDate' }}
        </time>
      </div>
    </div>
  `,
})
export class RecommendedCardComponent {
  contentlet = input.required<Contentlet>();

  uveMode = UVE_MODE;

  editContentlet(contentlet: Contentlet) {
    editContentlet(contentlet);
  }
}
