// examples/astro/src/components/content-types/Product.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface ProductProps extends DotCMSBasicContentlet {
  salePrice: number;
  retailPrice: number;
  urlTitle: string;
}
function Product({
  image,
  title,
  salePrice,
  retailPrice,
  urlTitle,
}: ProductProps) {
  const formatPrice = (price: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
    }).format(price);
  };

  return (
    <div className="overflow-hidden bg-white rounded-sm shadow-lg">
      <div className="p-4">
        {image && (
          <img
            className="object-contain w-full max-h-60"
            src={`${image.idPath}`}
            width={100}
            height={100}
            alt="Activity Image"
          />
        )}
      </div>
      <div className="px-6 py-4 bg-slate-100">
        <div className="mb-2 text-xl font-bold line-clamp-1">{title}</div>
        {retailPrice && salePrice ? (
          <>
            <div className="text-gray-500 line-through">
              {formatPrice(retailPrice)}
            </div>
            <div className="text-3xl font-bold ">{formatPrice(salePrice)}</div>
          </>
        ) : (
          <>
            <div className="min-h-6" />
            <div className="text-3xl font-bold">
              {retailPrice ? formatPrice(retailPrice) : formatPrice(salePrice)}
            </div>
          </>
        )}
        <a
          href={`/store/products/${urlTitle || "#"}`}
          className="inline-block px-4 py-2 mt-4 text-white bg-green-500 rounded-sm hover:bg-green-600"
        >
          Buy Now
        </a>
      </div>
    </div>
  );
}

export default Product;

// examples/angular/src/app/dotcms/components/product/product.component.ts
import { JsonPipe, NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { Product } from '../../types/contentlet.model';

@Component({
    selector: 'app-product',
    imports: [RouterLink, NgOptimizedImage],
    template: ` <div class="overflow-hidden bg-white rounded shadow-lg my-2">
        <div class="p-4">
            @if (contentlet().image.idPath; as idPath) {
                <img class="w-full" [ngSrc]="idPath" width="100" height="100" alt="Product Image" />
            }
        </div>
        <div class="px-6 py-4 bg-slate-100">
            <div class="mb-2 text-xl font-bold">{{ contentlet().title }}</div>
            @if (contentlet().retailPrice && contentlet().salePrice) {
                <div class="text-gray-500 line-through">{{ $retailPrice() }}</div>
                <div class="text-3xl font-bold">{{ $salePrice() }}</div>
            } @else {
                <div class="text-3xl font-bold">
                    {{ contentlet()['retailPrice'] ? $retailPrice() : $salePrice() }}
                </div>
            }
            <a
                [routerLink]="'/store/products/' + contentlet().urlTitle || '#'"
                class="inline-block px-4 py-2 mt-4 text-white bg-green-500 rounded hover:bg-green-600">
                Buy Now
            </a>
        </div>
    </div>`,
    styleUrl: './product.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ProductComponent {
    contentlet = input.required<Product>();

    $salePrice = computed(() => this.formatPrice(this.contentlet().salePrice));

    $retailPrice = computed(() => this.formatPrice(this.contentlet().retailPrice));

    protected get retailPrice() {
        return this.formatPrice(this.contentlet().retailPrice);
    }

    formatPrice(price: number) {
        if (!price || price === null) {
            return '';
        }

        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: 'USD'
        }).format(price);
    }
}
