// examples/nextjs/src/components/content-types/Banner.tsx
'use client';

import { DotCMSEditableText } from '@dotcms/react';
import Image from 'next/image';
import Link from 'next/link';

import type { ContentTypeProps, DotCMSImage } from '@/types/content';

type BannerProps = ContentTypeProps & {
    caption?: string;
    image?: DotCMSImage;
    link?: string;
    buttonText?: string;
};

function Banner(contentlet: BannerProps) {
    const { title, caption, image, link, buttonText, dotStyleProperties } = contentlet;

    // Extract style properties with defaults
    const titleSize = dotStyleProperties?.['title-size'] || 'text-6xl';
    const captionSize = dotStyleProperties?.['caption-size'] || 'text-xl';
    const titleStyle = dotStyleProperties?.['title-style'] || {};
    const textAlignment = dotStyleProperties?.['text-alignment'] || 'center';
    const overlayStyle = dotStyleProperties?.['overlay-style'] || 'none';
    const buttonColor = dotStyleProperties?.['button-color'] || 'blue';
    const buttonSize = dotStyleProperties?.['button-size'] || 'medium';
    const buttonStyle = dotStyleProperties?.['button-style'] || {};

    // Build title classes
    const titleClasses = [
        'mb-2',
        titleSize,
        titleStyle.bold ? 'font-bold' : 'font-normal',
        titleStyle.italic ? 'italic' : '',
        titleStyle.underline ? 'underline' : '',
        'text-white',
        'text-shadow'
    ]
        .filter(Boolean)
        .join(' ');

    // Build caption classes
    const captionClasses = ['mb-4', captionSize, 'text-white', 'text-shadow'].join(' ');

    // Get alignment classes
    const getAlignmentClasses = () => {
        switch (textAlignment) {
            case 'left':
                return 'items-start text-left';
            case 'right':
                return 'items-end text-right';
            case 'center':
            default:
                return 'items-center text-center';
        }
    };

    // Get overlay classes
    const getOverlayClasses = () => {
        switch (overlayStyle) {
            case 'dark':
                return 'bg-black/40';
            case 'light':
                return 'bg-white/20';
            case 'gradient':
                return 'bg-gradient-to-b from-black/50 via-transparent to-black/50';
            case 'none':
            default:
                return '';
        }
    };

    // Get button color classes
    const getButtonColorClasses = () => {
        const colorMap: Record<string, string> = {
            blue: 'bg-blue-500 hover:bg-blue-700',
            green: 'bg-green-500 hover:bg-green-700',
            red: 'bg-red-500 hover:bg-red-700',
            purple: 'bg-purple-500 hover:bg-purple-700',
            orange: 'bg-orange-500 hover:bg-orange-700',
            teal: 'bg-teal-500 hover:bg-teal-700'
        };
        return colorMap[buttonColor] || colorMap.blue;
    };

    // Get button size classes
    const getButtonSizeClasses = () => {
        switch (buttonSize) {
            case 'small':
                return 'px-3 py-2 text-base';
            case 'large':
                return 'px-6 py-4 text-2xl';
            case 'medium':
            default:
                return 'px-4 py-2 text-xl';
        }
    };

    // Get button style classes
    const getButtonStyleClasses = () => {
        const classes = [];
        if (buttonStyle.rounded) {
            classes.push('rounded-lg');
        } else if (buttonStyle['full-rounded']) {
            classes.push('rounded-full');
        } else {
            classes.push('rounded-sm');
        }
        if (buttonStyle.shadow) {
            classes.push('shadow-lg');
        }
        return classes.join(' ');
    };

    const buttonClasses = [
        'transition duration-300',
        'text-white',
        'font-bold',
        getButtonColorClasses(),
        getButtonSizeClasses(),
        getButtonStyleClasses()
    ].join(' ');

    return (
        <div className="relative w-full p-4 bg-gray-200 h-96">
            {image?.identifier && (
                <Image src={image?.identifier} fill={true} className="object-cover" alt={title} />
            )}
            {overlayStyle !== 'none' && (
                <div className={`absolute inset-0 ${getOverlayClasses()}`} />
            )}
            <div
                className={`absolute inset-0 flex flex-col justify-center p-4 ${getAlignmentClasses()} text-white`}>
                <h2 className={titleClasses}>
                    <DotCMSEditableText contentlet={contentlet} fieldName="title" />
                </h2>
                {caption && <p className={captionClasses}>{caption}</p>}
                {link && (
                    <Link className={buttonClasses} href={link}>
                        {buttonText || 'See more'}
                    </Link>
                )}
            </div>
        </div>
    );
}

export default Banner;

// examples/angular/src/app/dotcms/components/banner/banner.component.ts
import { NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { DotCMSEditableTextComponent } from '@dotcms/angular';

import { Banner } from '../../types/contentlet.model';

interface BannerDotStyleProperties {
  'title-size'?: string;
  'caption-size'?: string;
  'title-style'?: {
    bold?: boolean;
    italic?: boolean;
    underline?: boolean;
  };
  'text-alignment'?: 'left' | 'center' | 'right';
  'overlay-style'?: 'none' | 'dark' | 'light' | 'gradient';
  'button-color'?: 'blue' | 'green' | 'red' | 'purple' | 'orange' | 'teal';
  'button-size'?: 'small' | 'medium' | 'large';
  'button-style'?: {
    rounded?: boolean;
    'full-rounded'?: boolean;
    shadow?: boolean;
  };
}

@Component({
  selector: 'app-banner',
  imports: [RouterLink, NgOptimizedImage, DotCMSEditableTextComponent],
  template: `<div class="relative w-full p-4 bg-gray-200 h-96">
    @if (contentlet().image.identifier; as imageIdentifier) {
      <img
        class="object-cover w-full"
        [ngSrc]="imageIdentifier"
        [alt]="contentlet().title"
        fill
        priority
      />
    }
    @if (overlayStyle() !== 'none') {
      <div [class]="overlayClasses()"></div>
    }
    <div [class]="contentContainerClasses()">
      <h2 [class]="titleClasses()">
        <dotcms-editable-text fieldName="title" [contentlet]="contentlet()" />
      </h2>
      @if (contentlet().caption) {
        <p [class]="captionClasses()">{{ contentlet().caption }}</p>
      }
      @if (contentlet().link) {
        <a
          [class]="buttonClasses()"
          [routerLink]="contentlet().link"
        >
          {{ contentlet().buttonText || 'See more' }}
        </a>
      }
    </div>
  </div>`,
  styleUrl: './banner.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerComponent {
  contentlet = input.required<Banner>();

  dotStyleProperties = computed(() => this.contentlet().dotStyleProperties as BannerDotStyleProperties);

  // Computed properties for style values with defaults
  titleSize = computed(() => this.dotStyleProperties()?.['title-size'] || 'text-6xl');
  captionSize = computed(() => this.dotStyleProperties()?.['caption-size'] || 'text-xl');
  titleStyle = computed(() => this.dotStyleProperties()?.['title-style'] || {});
  textAlignment = computed(() => this.dotStyleProperties()?.['text-alignment'] || 'center');
  overlayStyle = computed(() => this.dotStyleProperties()?.['overlay-style'] || 'none');
  buttonColor = computed(() => this.dotStyleProperties()?.['button-color'] || 'blue');
  buttonSize = computed(() => this.dotStyleProperties()?.['button-size'] || 'medium');
  buttonStyle = computed(() => this.dotStyleProperties()?.['button-style'] || {});

  // Computed classes
  titleClasses = computed(() => {
    const style = this.titleStyle();
    const classes = [
      'mb-2',
      this.titleSize(),
      style.bold ? 'font-bold' : 'font-normal',
      style.italic ? 'italic' : '',
      style.underline ? 'underline' : '',
      'text-white',
      'text-shadow'
    ].filter(Boolean);
    return classes.join(' ');
  });

  captionClasses = computed(() => {
    return ['mb-4', this.captionSize(), 'text-white', 'text-shadow'].join(' ');
  });

  alignmentClasses = computed(() => {
    switch (this.textAlignment()) {
      case 'left':
        return 'items-start text-left';
      case 'right':
        return 'items-end text-right';
      case 'center':
      default:
        return 'items-center text-center';
    }
  });

  contentContainerClasses = computed(() => {
    return [
      'absolute',
      'inset-0',
      'flex',
      'flex-col',
      'justify-center',
      'p-4',
      this.alignmentClasses(),
      'text-white'
    ].join(' ');
  });

  overlayClasses = computed(() => {
    switch (this.overlayStyle()) {
      case 'dark':
        return 'absolute inset-0 bg-black/40';
      case 'light':
        return 'absolute inset-0 bg-white/20';
      case 'gradient':
        return 'absolute inset-0 bg-gradient-to-b from-black/50 via-transparent to-black/50';
      case 'none':
      default:
        return '';
    }
  });

  buttonColorClasses = computed(() => {
    const colorMap: Record<string, string> = {
      blue: 'bg-blue-500 hover:bg-blue-700',
      green: 'bg-green-500 hover:bg-green-700',
      red: 'bg-red-500 hover:bg-red-700',
      purple: 'bg-purple-500 hover:bg-purple-700',
      orange: 'bg-orange-500 hover:bg-orange-700',
      teal: 'bg-teal-500 hover:bg-teal-700'
    };
    return colorMap[this.buttonColor()] || colorMap['blue'];
  });

  buttonSizeClasses = computed(() => {
    switch (this.buttonSize()) {
      case 'small':
        return 'px-3 py-2 text-base';
      case 'large':
        return 'px-6 py-4 text-2xl';
      case 'medium':
      default:
        return 'px-4 py-2 text-xl';
    }
  });

  buttonStyleClasses = computed(() => {
    const style = this.buttonStyle();
    const classes: string[] = [];
    
    if (style.rounded) {
      classes.push('rounded-lg');
    } else if (style['full-rounded']) {
      classes.push('rounded-full');
    } else {
      classes.push('rounded-sm');
    }
    
    if (style.shadow) {
      classes.push('shadow-lg');
    }
    
    return classes.join(' ');
  });

  buttonClasses = computed(() => {
    return [
      'transition',
      'duration-300',
      'text-white',
      'font-bold',
      this.buttonColorClasses(),
      this.buttonSizeClasses(),
      this.buttonStyleClasses()
    ].join(' ');
  });
}
