// examples/angular/src/app/pages/components/footer/blogs/blogs.component.ts
import {
  Component,
  OnInit,
  inject,
  signal,
} from '@angular/core';
import { Contentlet } from '@dotcms/client/src/lib/client/content/shared/types';
import { DotCmsClient } from '@dotcms/client';
import { ContentletsComponent } from '../../../../shared/contentlets/contentlets.component';
import { DOTCMS_CLIENT_TOKEN } from '../../../../app.config';
import { GenericContentlet } from '../..';

@Component({
  selector: 'app-blogs',
  standalone: true,
  imports: [ContentletsComponent],
  template: ` <div class="flex flex-col">
    <h2 class="mb-7 text-2xl font-bold text-black">Latest Blog Posts</h2>
    @if (!!blogs().length) {
    <app-contentlets [contentlets]="blogs()" />
    }
  </div>`,
})
export class BlogsComponent implements OnInit {
  private readonly client = inject<DotCmsClient>(DOTCMS_CLIENT_TOKEN);

  readonly blogs = signal<Contentlet<GenericContentlet>[]>([]);

  ngOnInit(): void {
    this.client.content
      .getCollection<GenericContentlet>('Blog')
      .limit(3)
      .sortBy([
        {
          field: 'modDate',
          order: 'desc',
        },
      ])
      .then((response) => {
        this.blogs.set(response.contentlets);
      })
      .catch((error) => {
        console.error('Error fetching Blogs', error);
      });
  }
}

// examples/astro/src/react/layout/footer/components/blogs.tsx
import { useEffect, useState } from "react";

import type { DotCMSBasicContentlet } from "@dotcms/types";
import { Contentlets } from "@react/shared/contentlets";
import { dotCMSClient } from "@utils/client";

export const Blogs = () => {
  const [blogs, setBlogs] = useState<DotCMSBasicContentlet[]>([]);

  useEffect(() => {
    dotCMSClient.content
      .getCollection("Blog")
      .sortBy([
        {
          field: "modDate",
          order: "desc",
        },
      ])
      .limit(3)
      .then((response) => {
        setBlogs(response.contentlets);
      })
      .catch((error) => {
        console.error(`Error fetching Blogs`, error);
      });
  }, []);

  return (
    <div className="flex flex-col">
      <h2 className="text-2xl font-bold mb-7 text-black">Latest Blog Posts</h2>
      {!!blogs.length && <Contentlets contentlets={blogs} />}
    </div>
  );
};
