// examples/angular/src/app/shared/components/footer/components/destinations/destinations.component.ts
import { Component, input } from '@angular/core';

import { RecommendedCardComponent } from '../recommended-card/recommended-card.component';

import { Destination } from '../../../../contentlet.model';

@Component({
    selector: 'app-destinations',
    imports: [RecommendedCardComponent],
    template: ` <div class="flex flex-col">
        <h2 class="mb-7 text-2xl font-bold text-black">Popular Destinations</h2>
        <div class="flex flex-col gap-5">
            @for (destination of destinations(); track destination.identifier) {
            <app-recommended-card [contentlet]="destination" />
            }
        </div>
    </div>`
})
export class DestinationsComponent {
    destinations = input<Destination[]>([]);
}

// examples/astro/src/react/layout/footer/components/destinations.tsx
import RecommendedCard from "@components/react/RecommendedCard";

export default function Destinations({ destinations }: { destinations: any }) {
    if (!destinations?.length) return null;

    return (
        <div className="flex flex-col">
            <h2 className="text-2xl font-bold mb-7 text-white">
                Popular Destinations
            </h2>
            <div className="flex flex-col gap-5">
                {destinations.map((destination: any) => (
                    <RecommendedCard
                        key={destination.identifier}
                        contentlet={destination}
                    />
                ))}
            </div>
        </div>
    );
}
