// examples/angular/src/app/components/destinations/destinations.component.ts
import { Component, inject, signal } from '@angular/core';
import { DOTCMS_CLIENT_TOKEN } from '../../client-token/dotcms-client';
import { GenericContentlet } from '../../utils';
import { ContentletsComponent } from '../contentlets/contentlets.component';
import { Contentlet } from '@dotcms/client/src/lib/client/content/shared/types';

@Component({
  selector: 'app-destinations',
  standalone: true,
  imports: [ContentletsComponent],
  template: ` <div class="flex flex-col">
    <h2 class="text-2xl font-bold mb-7 text-black">Popular Destinations</h2>
    @if(!!destinations().length) {
    <app-contentlets [contentlets]="destinations()" /> }
  </div>`,
})
export class DestinationsComponent {
  private readonly client = inject(DOTCMS_CLIENT_TOKEN);

  readonly destinations = signal<Contentlet<GenericContentlet>[]>([]);

  constructor() {
    this.client.content
      .getCollection<GenericContentlet>('Destination')
      .limit(3)
      .sortBy([
        {
          field: 'modDate',
          order: 'desc',
        },
      ])
      .then((response) => {
        this.destinations.set(response.contentlets);
      })
      .catch((error) => {
        console.error('Error fetching Destinations', error);
      });
  }
}

// examples/astro/src/react/layout/footer/components/destinations.tsx
import { Contentlets } from "@react/shared/contentlets";
import type { DotCMSContentlet } from "@dotcms/types";
import { client } from "@utils/client";
import { useEffect, useState } from "react";

export const Destinations = () => {
  const [destinations, setDestinations] = useState<DotCMSContentlet[]>([]);

  useEffect(() => {
    client.content
      .getCollection("Destination")
      .sortBy([
        {
          field: "modDate",
          order: "desc",
        },
      ])
      .limit(3)
      .then((response) => {
        setDestinations(response.contentlets);
      })
      .catch((error) => {
        console.error(`Error fetching Destinations`, error);
      });
  }, []);

  return (
    <div className="flex flex-col">
      <h2 className="text-2xl font-bold mb-7 text-black">
        Popular Destinations
      </h2>
      {!!destinations.length && <Contentlets contentlets={destinations} />}
    </div>
  );
};
