// core-web/libs/sdk/angular/src/lib/components/dot-editable-text/dot-editable-text.component.ts
import { EditorComponent, TINYMCE_SCRIPT_SRC } from '@tinymce/tinymce-angular';
import { EventObj } from '@tinymce/tinymce-angular/editor/Events';

import {
    Component,
    ElementRef,
    HostListener,
    inject,
    Input,
    OnChanges,
    OnInit,
    Renderer2,
    ViewChild
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

import {
    CUSTOMER_ACTIONS,
    DotCmsClient,
    isInsideEditor,
    postMessageToEditor
} from '@dotcms/client';

import { TINYMCE_CONFIG, TINYMCE_FORMAT, TINYMCE_MODE } from './utils';

import { DotCMSContentlet } from '../../models';

@Component({
    selector: 'dot-editable-text',
    standalone: true,
    templateUrl: './dot-editable-text.component.html',
    styleUrl: './dot-editable-text.component.css',
    imports: [EditorComponent],
    providers: [
        {
            provide: TINYMCE_SCRIPT_SRC,
            useFactory: () => {
                return `${DotCmsClient.dotcmsUrl}/html/tinymce/tinymce.min.js`;
            }
        }
    ]
})
export class DotEditableTextComponent implements OnInit, OnChanges {
    @ViewChild(EditorComponent) editorComponent!: EditorComponent;

    @Input() mode: TINYMCE_MODE = 'plain';
    @Input() format: TINYMCE_FORMAT = 'text';
    @Input() contentlet!: DotCMSContentlet;
    @Input() fieldName = '';

    protected content = '';
    protected safeContent!: SafeHtml;
    protected init!: EditorComponent['init'];
    protected readonly isInsideEditor = isInsideEditor();

    readonly #sanitizer = inject<DomSanitizer>(DomSanitizer);
    readonly #renderer = inject<Renderer2>(Renderer2);
    readonly #elementRef = inject<ElementRef>(ElementRef);

    get editor() {
        return this.editorComponent.editor;
    }

    get onNumberOfPages() {
        return this.contentlet['onNumberOfPages'];
    }

    @HostListener('window:message', ['$event'])
    onMessage({ data }: MessageEvent) {
        const { name, payload } = data;
        if (name !== 'COPY_CONTENTLET_INLINE_EDITING_SUCCESS') {
            return;
        }

        const { oldInode, inode } = payload;
        const currentInode = this.contentlet.inode;

        if (currentInode === oldInode || currentInode === inode) {
            this.editorComponent.editor.focus();

            return;
        }
    }

    ngOnInit() {
        if (!this.isInsideEditor) {
            this.innerHTMLToElement();

            return;
        }

        this.init = {
            ...TINYMCE_CONFIG[this.mode],
            base_url: `${DotCmsClient.dotcmsUrl}/html/tinymce`
        };
    }

    ngOnChanges() {
        this.content = this.contentlet[this.fieldName] || '';
        this.safeContent = this.#sanitizer.bypassSecurityTrustHtml(this.content);
    }

    /**
     * Handle mouse down event
     *
     * @param {EventObj<MouseEvent>} { event }
     * @return {*}
     * @memberof DotEditableTextComponent
     */
    onMouseDown({ event }: EventObj<MouseEvent>) {
        if (this.onNumberOfPages <= 1 || this.editorComponent.editor.hasFocus()) {
            return;
        }

        const { inode, languageId: language } = this.contentlet;

        event.stopPropagation();
        event.preventDefault();

        try {
            postMessageToEditor({
                action: CUSTOMER_ACTIONS.COPY_CONTENTLET_INLINE_EDITING,
                payload: {
                    dataset: {
                        inode,
                        language,
                        fieldName: this.fieldName
                    }
                }
            });
        } catch (error) {
            console.error('Failed to post message to editor:', error);
        }
    }
    /**
     * Handle focus out event
     *
     * @return {*}
     * @memberof DotEditableTextComponent
     */
    onFocusOut() {
        const content = this.editor.getContent({ format: this.format });

        if (!this.editor.isDirty() || !this.didContentChange(content)) {
            return;
        }

        const { inode, languageId: langId } = this.contentlet;

        try {
            postMessageToEditor({
                action: CUSTOMER_ACTIONS.UPDATE_CONTENTLET_INLINE_EDITING,
                payload: {
                    content,
                    dataset: {
                        inode,
                        langId,
                        fieldName: this.fieldName
                    }
                }
            });
        } catch (error) {
            console.error('Failed to post message to editor:', error);
        }
    }

    /**
     * inner HTML to element
     *
     * @private
     * @param {string} editedContent
     * @return {*}
     * @memberof DotEditableTextComponent
     */
    private innerHTMLToElement() {
        const element = this.#elementRef.nativeElement;
        this.#renderer.setProperty(element, 'innerHTML', this.content);
    }

    /**
     * Check if the content has changed
     *
     * @private
     * @param {string} editedContent
     * @return {*}
     * @memberof DotEditableTextComponent
     */
    private didContentChange(editedContent: string) {
        return this.content !== editedContent;
    }
}

@if (isInsideEditor) {
<editor
    [init]="init"
    [inline]="true"
    [initialValue]="content"
    (onMouseDown)="onMouseDown($event)"
    (onFocusIn)="onFocusIn($event)"
    (onFocusOut)="onFocusOut($event)" />
} @else { @if(format === 'html') {
<div [innerHTML]="safeContent"></div>
} @else {
{{ content }}
} }

// core-web/libs/sdk/react/src/lib/components/DotEditableText/DotEditableText.tsx
import { Editor } from '@tinymce/tinymce-react';
import { useEffect, useRef, useState } from 'react';

import {
    isInsideEditor as isInsideEditorFn,
    postMessageToEditor,
    CUSTOMER_ACTIONS,
    DotCmsClient
} from '@dotcms/client';

import { DotEditableTextProps, TINYMCE_CONFIG } from './utils';

export function DotEditableText({
    mode = 'plain',
    format = 'text',
    contentlet,
    fieldName = ''
}: Readonly<DotEditableTextProps>) {
    const editorRef = useRef<Editor['editor'] | null>(null);
    const [isInsideEditor, setIsInsideEditor] = useState(false);
    const [content, setContent] = useState(contentlet[fieldName] || '');

    useEffect(() => {
        const isInsideEditor = isInsideEditorFn();
        setIsInsideEditor(isInsideEditor);

        if (!isInsideEditor) {
            return;
        }

        const content = contentlet[fieldName] || '';
        editorRef.current?.setContent(content, { format });
        setContent(content);
    }, [contentlet, fieldName, format]);

    useEffect(() => {
        const onMessage = ({ data }: MessageEvent) => {
            const { name, payload } = data;
            if (name !== 'COPY_CONTENTLET_INLINE_EDITING_SUCCESS') {
                return;
            }

            const { oldInode, inode } = payload;
            const currentInode = contentlet.inode;
            const shouldFocus = currentInode === oldInode || currentInode === inode;

            if (shouldFocus) {
                editorRef.current?.focus();
            }
        };

        window.addEventListener('message', onMessage);

        return () => {
            window.removeEventListener('message', onMessage);
        };
    }, [contentlet.inode]);

    const onMouseDown = (event: MouseEvent) => {
        const { onNumberOfPages = 1 } = contentlet;

        if (onNumberOfPages <= 1 || editorRef.current?.hasFocus()) {
            return;
        }

        const { inode, languageId: language } = contentlet;

        event.stopPropagation();
        event.preventDefault();

        try {
            postMessageToEditor({
                action: CUSTOMER_ACTIONS.COPY_CONTENTLET_INLINE_EDITING,
                payload: {
                    dataset: {
                        inode,
                        language,
                        fieldName
                    }
                }
            });
        } catch (error) {
            console.error('Failed to post message to editor:', error);
        }
    };

    const onFocusOut = () => {
        const editedContent = editorRef.current?.getContent({ format: format }) || '';

        if (!editorRef.current?.isDirty() || !didContentChange(editedContent)) {
            return;
        }

        const { inode, languageId: langId } = contentlet;

        try {
            postMessageToEditor({
                action: CUSTOMER_ACTIONS.UPDATE_CONTENTLET_INLINE_EDITING,
                payload: {
                    content: editedContent,
                    dataset: {
                        inode,
                        langId,
                        fieldName
                    }
                }
            });
        } catch (error) {
            console.error('Failed to post message to editor:', error);
        }
    };

    const didContentChange = (editedContent: string) => {
        return content !== editedContent;
    };

    if (!isInsideEditor) {
        // We can let the user pass the Child Component and create a root to get the HTML for the editor
        return <div dangerouslySetInnerHTML={{ __html: content }} />;
    }

    return (
        <Editor
            tinymceScriptSrc={`${DotCmsClient.dotcmsUrl}/ext/tinymcev7/tinymce.min.js`}
            inline={true}
            onInit={(_, editor) => (editorRef.current = editor)}
            init={TINYMCE_CONFIG[mode]}
            initialValue={content}
            onMouseDown={onMouseDown}
            onFocusOut={onFocusOut}
        />
    );
}

export default DotEditableText;
