// examples/nextjs/src/components/content-types/Image.tsx
import Image from 'next/image';

import type { DotCMSImage } from '@/types/content';

interface ImageComponentProps {
    fileAsset?: DotCMSImage;
    title?: string;
    description?: string;
}

function ImageComponent({ fileAsset, title, description }: ImageComponentProps) {
    return (
        <div className="relative overflow-hidden bg-white rounded-sm shadow-lg group">
            <div className="relative w-full bg-gray-200 h-96">
                {fileAsset?.identifier && (
                    <Image
                        src={fileAsset?.identifier}
                        fill={true}
                        className="object-cover w-full h-full"
                        alt={title ?? ''}
                    />
                )}
            </div>
            <div className="absolute bottom-0 w-full px-6 py-8 text-white transition-transform duration-300 translate-y-full bg-orange-500 bg-opacity-80 group-hover:translate-y-0">
                <div className="mb-2 text-2xl font-bold">{title}</div>
                <p className="text-base">{description}</p>
            </div>
        </div>
    );
}

export default ImageComponent;

// examples/angular/src/app/dotcms/components/image/image.component.ts
import { NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { ImageContentlet } from '../../types/contentlet.model';

@Component({
  selector: 'app-image',
  imports: [NgOptimizedImage],
  template: `<div
    class="overflow-hidden relative mb-4 bg-white rounded shadow-lg group"
  >
    <div class="relative w-full h-96 bg-gray-200">
      <img
        class="object-cover"
        [ngSrc]="contentlet().fileAsset"
        [alt]="contentlet().title"
        fill
      />
    </div>
    <div
      class="absolute bottom-0 px-6 py-8 w-full text-white bg-orange-500 bg-opacity-80 transition-transform duration-300 translate-y-full w-100 group-hover:translate-y-0"
    >
      <div class="mb-2 text-2xl font-bold">{{ contentlet().title }}</div>
      <p class="text-base">{{ contentlet().description }}</p>
    </div>
  </div>`,
  styleUrl: './image.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ImageComponent {
  contentlet = input.required<ImageContentlet>();
}
