// examples/vuejs/src/components/content-types/PageForm.vue
<script setup lang="ts">
import ContactUs from '@/components/forms/ContactUs.vue';
import { useIsEditMode } from '@/composables/useIsEditMode';
import type { ContentTypeProps } from '@/types/content';

const props = defineProps<ContentTypeProps & { formType?: string; description?: string }>();

const isEditMode = useIsEditMode();
</script>

<template>
    <ContactUs v-if="formType === 'contact-us'" :description="description" />
    <div v-else-if="isEditMode">
        <h4>There is no form component for this form type: {{ formType }}</h4>
    </div>
</template>

// examples/astro/src/components/content-types/PageForm.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";
import { useIsEditMode } from "@/hooks";

import { ContactUs } from "@/components/ui";

interface PageFormProps extends DotCMSBasicContentlet {
  formType: string;
  description: string;
}

export default function PageForm(contentlet: PageFormProps) {
  const { formType } = contentlet;
  const isEditMode = useIsEditMode();

  if (formType === "contact-us") {
    return <ContactUs {...contentlet} />;
  }

  if (isEditMode) {
    return (
      <div>
        <h4>There is no form component for this form type: {formType}</h4>
      </div>
    );
  }

  return null;
}
