// examples/angular/src/app/content-types/store-product-list/store-product-list.component.ts
import { Component, computed, input } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { Product, StoreProductList } from '../../shared/contentlet.model';

type ProductWithDiscount = Product & { hasDiscount?: boolean; discountPercentage?: number };

@Component({
    selector: 'app-store-product-list',
    imports: [NgOptimizedImage],
    templateUrl: './store-product-list.component.html'
})
export class StoreProductListComponent {
    contentlet = input.required<StoreProductList>();

    products = computed(() => this.contentlet().widgetCodeJSON?.products || []);

    hasProducts = computed(() => this.products() && this.products().length > 0);

    productsWithDiscount = computed<ProductWithDiscount[]>(() =>
        this.products().map((product) => {
            const hasDiscount = this.#hasDiscount(product);

            return hasDiscount
                ? {
                      ...product,
                      hasDiscount,
                      discountPercentage: this.#discountPercentage(product)
                  }
                : product;
        })
    );

    #hasDiscount(product: Product): boolean {
        const { salePrice, retailPrice } = product;
        return Boolean(salePrice && retailPrice && Number(salePrice) < Number(retailPrice));
    }

    #discountPercentage(product: Product): number {
        const { salePrice, retailPrice } = product;
        return Math.round((1 - Number(salePrice) / Number(retailPrice)) * 100);
    }

    onProductClick(title: string): void {
        alert('Selected Product: ' + title);
    }
}

@if (hasProducts()) {
<div>
    <h2 class="text-4xl font-bold mb-4">{{ contentlet().widgetTitle }}</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        @for (product of productsWithDiscount(); track product.identifier) {
        <div class="group relative" (click)="onProductClick(product.title)">
            <div
                class="bg-white rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-300 flex flex-col h-full">
                <div class="relative aspect-square w-full overflow-hidden bg-gray-100">
                    <img
                        [ngSrc]="product.inode"
                        [alt]="product.title"
                        fill
                        class="object-cover object-center w-full h-full group-hover:scale-105 transition-transform duration-300" />
                </div>

                <div class="p-4 flex flex-col flex-grow">
                    <h3
                        class="text-gray-900 font-medium text-sm mb-2 line-clamp-2 group-hover:text-red-500 transition-colors">
                        {{ product.title }}
                    </h3>

                    <div class="mt-auto pt-2 flex items-center justify-between">
                        @if (product?.hasDiscount) {
                        <div>
                            <span class="text-red-600 font-semibold mr-2">
                                ${{ product.salePrice }}
                            </span>
                            <span class="text-gray-500 text-sm line-through">
                                ${{ product.retailPrice }}
                            </span>
                        </div>
                        } @else {
                        <span class="text-gray-900 font-semibold">${{ product.retailPrice }}</span>
                        } @if (product?.hasDiscount) {
                        <span class="bg-red-100 text-red-800 text-xs px-2 py-1 rounded-full">
                            {{ product.discountPercentage }}% OFF
                        </span>
                        }
                    </div>
                </div>
            </div>
        </div>
        }
    </div>
</div>
}

// examples/astro/src/components/content-types/StoreProductList.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";
import { EditButton } from "../ui/EditButton";
interface Product extends DotCMSBasicContentlet {
  inode: string;
  title: string;
  retailPrice: number;
  salePrice: number;
}

interface StoreProductListProps extends DotCMSBasicContentlet {
  widgetTitle: string;
  widgetCodeJSON: { products: Product[] };
}

export default function StoreProductList({
  widgetTitle,
  widgetCodeJSON,
}: StoreProductListProps) {
  const products = widgetCodeJSON.products;

  if (!products) {
    console.warn("No products found in StoreProductList");
    return null;
  }

  return (
    <div>
      <h2 className="text-4xl font-bold mb-4">{widgetTitle}</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {products?.map((product) => (
          <ProductCard key={product.inode} product={product} />
        ))}
      </div>
    </div>
  );
}

function ProductCard({ product }: { product: Product }) {
  const { image, title, retailPrice, salePrice } = product;

  const hasDiscount =
    salePrice && retailPrice && Number(salePrice) < Number(retailPrice);

  return (
    <div
      className="group relative"
      onClick={() => alert("Selected Product: " + title)}
    >
      <EditButton contentlet={product} />
      <div className="bg-white rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-300 flex flex-col h-full">
        <div className="relative aspect-square w-full overflow-hidden bg-gray-100">
          <img
            src={`/dA/${image.identifier}`}
            alt={title}
            className="object-cover object-center group-hover:scale-105 transition-transform duration-300"
          />
        </div>

        <div className="p-4 flex flex-col grow">
          <h3 className="text-gray-900 font-medium text-sm mb-2 line-clamp-2 group-hover:text-blue-600 transition-colors">
            {title}
          </h3>

          <div className="mt-auto pt-2 flex items-center justify-between">
            {hasDiscount ? (
              <div>
                <span className="text-red-600 font-semibold mr-2">
                  ${salePrice}
                </span>
                <span className="text-gray-500 text-sm line-through">
                  ${retailPrice}
                </span>
              </div>
            ) : (
              <span className="text-gray-900 font-semibold">
                ${retailPrice}
              </span>
            )}

            {hasDiscount && (
              <span className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded-full">
                {Math.round(
                  (1 - Number(salePrice) / Number(retailPrice)) * 100,
                )}
                % OFF
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
