// examples/angular-ssr/src/app/components/navigation/navigation.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { DotCMSNavigationItem } from '@dotcms/types';

@Component({
    selector: 'app-navigation',
    imports: [RouterLink],
    template: `
        <nav>
            <ul class="flex space-x-4 text-white">
                <li>
                    <a [routerLink]="'/'">Home</a>
                </li>
                @for (item of items(); track $index) {
                    <li>
                        <a [routerLink]="item.href" target="{{ item.target }}">{{ item.title }}</a>
                    </li>
                }
            </ul>
        </nav>
    `,
    styleUrl: './navigation.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NavigationComponent {
    items = input.required<DotCMSNavigationItem[]>();
}

// examples/astro/src/react/layout/navigation.tsx
import type { DotcmsNavigationItem } from "@dotcms/types";
import type { FC } from "react";

export type NavigationProps = {
  items?: DotcmsNavigationItem[];
  className?: string;
};

export const Navigation: FC<NavigationProps> = ({ items, className }) => {
  const currentQueryParams = window.location.search;

  return (
    <nav className={className}>
      <ul className="flex space-x-4 text-white">
        <li>
          <a href={`/${currentQueryParams}`}> Home</a>
        </li>
        {items?.map((item) => (
          <li key={item.folder}>
            <a href={item.href + currentQueryParams} target={item.target}>
              {item.title}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
};
