// examples/angular/src/app/pages/content-types/banner/banner.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DotCMSContentlet } from '@dotcms/angular';



@Component({
  selector: 'app-banner',
  standalone: true,
  imports: [RouterLink],
  template: `<div class="relative w-full bg-gray-200 h-96 flex justify-center items-center overflow-hidden">
    <img
      class="object-cover w-full"
      [src]="contentlet.image + '?language_id' + contentlet.languageId"
      [alt]="contentlet.title"
    />
    <div
      class="absolute inset-0 flex flex-col items-center justify-center p-4 text-center text-white"
    >
      <h2 class="mb-2 text-6xl font-bold text-shadow">
        {{ contentlet.title }}
      </h2>
      <p class="mb-4 text-xl text-shadow">{{ contentlet['caption'] }}</p>
      <a
        class="p-4 text-xl transition duration-300 bg-red-400 rounded hover:bg-purple-600"
        [routerLink]="contentlet['link']"
      >
        {{ contentlet['buttonText'] }}
      </a>
    </div>
  </div>`,
  styleUrl: './banner.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerComponent {
  @Input() contentlet!: DotCMSContentlet;
}

// examples/astro/src/react/content-types/banner.js
import Image from "next/image";
import Link from "next/link";

function Banner({ title, image, caption, buttonText, link }) {
    return (
        <div className="relative w-full p-4 bg-gray-200 h-96">
            {image && (
                <Image
                    src={image?.idPath ?? image}
                    fill={true}
                    className="object-cover"
                    alt={title}
                />
            )}
            <div className="absolute inset-0 flex flex-col items-center justify-center p-4 text-center text-white">
                <h2 className="mb-2 text-6xl font-bold text-shadow">{title}</h2>
                <p className="mb-4 text-xl text-shadow">{caption}</p>
                <Link
                    className="p-4 text-xl transition duration-300 bg-purple-500 rounded hover:bg-purple-600"
                    href={link || "#"}
                >
                    {buttonText}
                </Link>
            </div>
        </div>
    );
}

export default Banner;
