// examples/vuejs/src/components/content-types/VtlInclude.vue
<script setup lang="ts">
import DestinationListing from '@/components/DestinationListing.vue';
import { useIsEditMode } from '@/composables/useIsEditMode';
import type { Destination } from '@/types/content';

/**
 * Renders VTL-scripted widgets by `componentType`. See:
 * https://dev.dotcms.com/docs/scripting-api#ResponseJSON
 */
const props = defineProps<{
    componentType?: string;
    widgetCodeJSON?: { destinations?: Destination[] };
}>();

const isEditMode = useIsEditMode();
</script>

<template>
    <DestinationListing
        v-if="componentType === 'destinationListing'"
        :destinations="widgetCodeJSON?.destinations" />
    <div v-else-if="isEditMode" class="bg-blue-100 p-4">
        <h4>No Component Type: {{ componentType || 'generic' }} Found for VTL Include</h4>
    </div>
</template>

// examples/astro/src/react/content-types/VtlInclude.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface VtlIncludeProps extends DotCMSBasicContentlet {
    componentType: string;
    widgetCodeJSON: {
        products: { inode: string; title: string; retailPrice: number; salePrice: number }[];
    };
}
export default function VtlInclude({ componentType, widgetCodeJSON }: VtlIncludeProps) {
    const isEditMode = false; // useIsEditMode();

    if (componentType === "destinationListing") {
        // return <DestinationListing {...widgetCodeJSON} />;

        return <div>Destination List</div>
    }

    if (isEditMode) {
        return (
            <div className="bg-blue-100 p-4">
                <h4>
                    No Component Type: {componentType || "generic"} Found for
                    VTL Include
                </h4>
            </div>
        );
    }

    return null;
}
