// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Image.tsx
import { BlockEditorNode } from '@dotcms/types';

interface DotCMSImageProps {
    src: string;
    alt: string;
    href?: string | null;
    target?: string | null;
    textWrap?: 'left' | 'right';
    textAlign?: string;
}

/**
 * Renders an image component for dotCMS.
 *
 * When the Block Editor assigns a link to the image, it is stored as `href` /
 * `target` on the `dotImage` node and the image is wrapped in an anchor. `href`
 * is `null` when the image has no link, in which case it renders bare. The
 * truthiness check also covers the transient `''` the editor writes while
 * unsetting a link.
 *
 * @param node - The node for the DotCMSImage component.
 * @returns The rendered image component.
 */
export const DotCMSImage = ({ node }: { node: BlockEditorNode }) => {
    const { src, alt, href, target, textWrap, textAlign } = node.attrs as DotCMSImageProps;

    let wrapperStyle: React.CSSProperties = {};

    if (textWrap === 'left') {
        wrapperStyle = { float: 'left', width: '50%', margin: '0 1rem 1rem 0' };
    } else if (textWrap === 'right') {
        wrapperStyle = { float: 'right', width: '50%', margin: '0 0 1rem 1rem' };
    } else if (textAlign) {
        wrapperStyle = { textAlign: textAlign as React.CSSProperties['textAlign'] };
    }

    const image = (
        <img
            alt={alt}
            src={src}
            style={textWrap ? { maxWidth: '100%', height: 'auto' } : undefined}
        />
    );

    return (
        <figure style={wrapperStyle}>
            {href ? (
                <a
                    href={href}
                    target={target ?? undefined}
                    // Guards against reverse tabnabbing when the link opens in a new tab.
                    rel={target === '_blank' ? 'noopener noreferrer' : undefined}>
                    {image}
                </a>
            ) : (
                image
            )}
        </figure>
    );
};

// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/image.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

@Component({
    selector: 'dotcms-block-editor-renderer-image',
    imports: [NgTemplateOutlet],
    template: `
        <figure [style]="$wrapperStyle()">
            @if ($href(); as href) {
                <!-- target/rel are attribute bindings so a null value omits the
                     attribute instead of rendering the string "null". -->
                <a [href]="href" [attr.target]="$target()" [attr.rel]="$rel()">
                    <ng-container [ngTemplateOutlet]="image" />
                </a>
            } @else {
                <ng-container [ngTemplateOutlet]="image" />
            }
        </figure>

        <ng-template #image>
            <img [alt]="attrs()?.['alt']" [src]="$srcURL()" />
        </ng-template>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DotImageBlock {
    readonly attrs = input<BlockEditorNode['attrs']>();

    protected readonly $srcURL = computed(() => this.attrs()?.['src']);

    /**
     * Link assigned to the image in the Block Editor, stored as `href` on the
     * `dotImage` node. `null` when the image has no link, in which case it
     * renders without an anchor. The truthiness check also covers the
     * transient `''` the editor writes while unsetting a link.
     */
    protected readonly $href = computed(() => this.attrs()?.['href'] || null);

    protected readonly $target = computed(() => this.attrs()?.['target'] || null);

    /** Guards against reverse tabnabbing when the link opens in a new tab. */
    protected readonly $rel = computed(() =>
        this.$target() === '_blank' ? 'noopener noreferrer' : null
    );

    protected readonly $wrapperStyle = computed(() => {
        const textWrap = this.attrs()?.['textWrap'];
        const textAlign = this.attrs()?.['textAlign'];

        if (textWrap === 'left') {
            return { float: 'left', width: '50%', margin: '0 1rem 1rem 0' };
        } else if (textWrap === 'right') {
            return { float: 'right', width: '50%', margin: '0 0 1rem 1rem' };
        } else if (textAlign) {
            return { 'text-align': textAlign };
        }

        return {};
    });
}
