// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Table.tsx
import React from 'react';

import { BlockEditorNode } from '@dotcms/types';

interface TableRendererProps {
    content: BlockEditorNode[];
    /**
     * Table-node attributes (`caption`, `ariaLabel`, `ariaLabelledby`). Optional for
     * back-compat with older payloads that don't carry these.
     */
    attrs?: BlockEditorNode['attrs'];
    blockEditorItem: React.FC<{
        content: BlockEditorNode[];
    }>;
}

/**
 * Renders a table block for the Block Editor.
 *
 * **Cell-type-aware**: each cell is emitted as `<th>` or `<td>` based on the node's
 * `type` (`tableHeader` vs `tableCell`) rather than its row position — so column-header
 * cells in any row (the result of "Toggle column header" in the editor) keep their
 * semantic `<th>` wrapper and the `scope` attribute reaches headless consumers.
 *
 * @param content - The table's child rows.
 * @param attrs - Optional table-level attributes (`caption`, `ariaLabel`, `ariaLabelledby`).
 * @param blockEditorItem - The Block Editor item component for nested content.
 */
export const TableRenderer: React.FC<TableRendererProps> = ({
    content,
    attrs,
    blockEditorItem
}: TableRendererProps) => {
    const BlockEditorItemComponent = blockEditorItem;

    const renderCellContent = (node: BlockEditorNode) => (
        <BlockEditorItemComponent content={node.content ?? []} />
    );

    const caption: string | undefined = attrs?.['caption'] || undefined;
    const ariaLabel: string | undefined = attrs?.['ariaLabel'] || undefined;
    const ariaLabelledBy: string | undefined = attrs?.['ariaLabelledby'] || undefined;

    return (
        <table aria-label={ariaLabel} aria-labelledby={ariaLabelledBy}>
            {caption ? <caption>{caption}</caption> : null}
            <tbody>
                {content.map((rowNode, rowIndex) => (
                    <tr key={`row-${rowIndex}`}>
                        {rowNode.content?.map((cellNode, cellIndex) => {
                            const colSpan = Number(cellNode.attrs?.['colspan'] || 1);
                            const rowSpan = Number(cellNode.attrs?.['rowspan'] || 1);
                            // Cell type — not row index — decides th vs td. Matches the
                            // VTL renderer (storyblock/render.vtl).
                            if (cellNode.type === 'tableHeader') {
                                return (
                                    <th
                                        key={`cell-${cellIndex}`}
                                        colSpan={colSpan}
                                        rowSpan={rowSpan}
                                        scope={cellNode.attrs?.['scope'] || undefined}>
                                        {renderCellContent(cellNode)}
                                    </th>
                                );
                            }
                            return (
                                <td key={`cell-${cellIndex}`} colSpan={colSpan} rowSpan={rowSpan}>
                                    {renderCellContent(cellNode)}
                                </td>
                            );
                        })}
                    </tr>
                ))}
            </tbody>
        </table>
    );
};

// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/table.component.ts
import { NgComponentOutlet } from '@angular/common';
import { Component, Input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

import { DotCMSBlockEditorItemComponent } from '../item/dotcms-block-editor-item.component';
@Component({
    selector: 'dotcms-block-editor-renderer-table',
    imports: [NgComponentOutlet],
    template: `
        <table
            [attr.aria-label]="attrs?.['ariaLabel'] || null"
            [attr.aria-labelledby]="attrs?.['ariaLabelledby'] || null">
            @if (attrs?.['caption']) {
                <caption>{{ attrs?.['caption'] }}</caption>
            }
            <tbody>
                @for (rowNode of content; track $index) {
                    <tr>
                        @for (cellNode of rowNode.content; track $index) {
                            <!--
                                Cell type — not row index — decides th vs td. Matches the
                                VTL renderer (storyblock/render.vtl) so headless markup
                                stays consistent with server-rendered pages.
                            -->
                            @if (cellNode.type === 'tableHeader') {
                                <th
                                    [attr.colspan]="cellNode.attrs?.['colspan'] || 1"
                                    [attr.rowspan]="cellNode.attrs?.['rowspan'] || 1"
                                    [attr.scope]="cellNode.attrs?.['scope'] || null">
                                    <ng-container
                                        *ngComponentOutlet="
                                            blockEditorItem;
                                            inputs: { content: cellNode.content }
                                        " />
                                </th>
                            } @else {
                                <td
                                    [attr.colspan]="cellNode.attrs?.['colspan'] || 1"
                                    [attr.rowspan]="cellNode.attrs?.['rowspan'] || 1">
                                    <ng-container
                                        *ngComponentOutlet="
                                            blockEditorItem;
                                            inputs: { content: cellNode.content }
                                        " />
                                </td>
                            }
                        }
                    </tr>
                }
            </tbody>
        </table>
    `
})
export class DotTableBlock {
    @Input() content: BlockEditorNode[] | undefined;
    /**
     * Table-node attributes (`caption`, `ariaLabel`, `ariaLabelledby`). Optional for
     * back-compat with older payloads that don't carry these.
     */
    @Input() attrs: BlockEditorNode['attrs'];
    blockEditorItem = DotCMSBlockEditorItemComponent;
}
