// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Video.tsx
import { BlockEditorNode } from '@dotcms/types';

interface DotCMSVideoProps {
    data: {
        identifier: string;
        thumbnail: string;
    };
    src: string;
    mimeType: string;
    width: number;
    height: number;
}

/**
 * Renders a video component for displaying videos.
 *
 * @param props - The properties for the video component.
 * @returns The rendered video component.
 */
export const DotCMSVideo = ({ node }: { node: BlockEditorNode }) => {
    const { data, src, mimeType, width, height } = node.attrs as DotCMSVideoProps;
    const poster = data?.thumbnail;
    const posterAttribute = poster ? { poster } : {};

    return (
        <video controls preload="metadata" width={width} height={height} {...posterAttribute}>
            <track default kind="captions" srcLang="en" />
            <source src={src} type={mimeType} />
            Your browser does not support the <code>video</code> element.
        </video>
    );
};

// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/video.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

@Component({
    selector: 'dotcms-block-editor-renderer-video',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <video
            [controls]="true"
            preload="metadata"
            [poster]="this.$posterURL()"
            [width]="attrs()?.['width']"
            [height]="attrs()?.['height']">
            <track default kind="captions" srclang="en" />
            <source [src]="this.$srcURL()" [type]="attrs()?.['mimeType']" />
            Your browser does not support the
            <code>video</code>
            element.
        </video>
    `
})
export class DotVideoBlock {
    readonly attrs = input<BlockEditorNode['attrs']>();

    protected readonly $srcURL = computed(() => this.attrs()?.['src']);

    protected readonly $posterURL = computed(() => this.attrs()?.['data']?.['thumbnail']);
}
