// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/video.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

@Component({
    selector: 'dotcms-block-editor-renderer-video',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <video
            [controls]="true"
            preload="metadata"
            [poster]="this.$posterURL()"
            [width]="attrs()?.['width']"
            [height]="attrs()?.['height']">
            <track default kind="captions" srclang="en" />
            <source [src]="this.$srcURL()" [type]="attrs()?.['mimeType']" />
            Your browser does not support the
            <code>video</code>
            element.
        </video>
    `
})
export class DotVideoBlock {
    readonly attrs = input<BlockEditorNode['attrs']>();

    protected readonly $srcURL = computed(() => this.attrs()?.['src']);

    protected readonly $posterURL = computed(() => this.attrs()?.['data']?.['thumbnail']);
}

// core-web/libs/sdk/react/src/lib/components/BlockEditorRenderer/blocks/Video.tsx
import { DotCmsClient } from '@dotcms/client';

import { ContentNode } from '../../../models/blocks.interface';

type DotCMSVideoProps = ContentNode['attrs'] & {
    data?: Record<string, string>;
};

/**
 * Renders a video component for displaying videos.
 *
 * @param props - The properties for the video component.
 * @returns The rendered video component.
 */
export const DotCMSVideo = (props: ContentNode) => {
    const { data, src, mimeType, width, height } = props.attrs as DotCMSVideoProps;
    const client = DotCmsClient.instance;

    const srcUrl = data?.identifier ? `${client.dotcmsUrl}${src}` : src;

    const poster = data?.thumbnail ? `${client.dotcmsUrl}${data?.thumbnail}` : 'poster-image.jpg';

    return (
        <video controls preload="metadata" poster={poster} width={width} height={height}>
            <track default kind="captions" srcLang="en" />
            <source src={srcUrl} type={mimeType} />
            Your browser does not support the <code>video</code> element.
        </video>
    );
};
