// examples/astro/src/react/layout/header.tsx


function Header({ children }) {
    return (
        <header className="flex items-center justify-between p-4 bg-blue-500">
            <div className="flex items-center">
                <h2 className="text-3xl font-bold text-white">
                    <a href="/">TravelLux</a>
                </h2>
            </div>
            {children}
        </header>
    );
}

export default Header;

// examples/angular/src/app/shared/components/header/header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ReorderButtonComponent } from '../reorder-button/reorder-button.component';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [ReorderButtonComponent],
    template: `
        <header class="flex items-center justify-between p-4 bg-red-400">
            <div class="flex items-center">
                <h2 class="text-3xl font-bold text-white">
                    <a routerLink="/">TravelLux with NG</a>
                </h2>
                <app-reorder-button />
            </div>
            <ng-content></ng-content>
        </header>
    `,
    styleUrl: './header.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeaderComponent {}
