// examples/astro/src/components/content-types/Activity.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

export interface ActivityProps extends DotCMSBasicContentlet {
  description: string;
  urlMap?: string;
  urlTitle?: string;
  widgetTitle?: string;
}

function Activity({
  title,
  description,
  image,
  inode,
  urlTitle,
}: ActivityProps) {
  return (
    <article className="p-4 overflow-hidden bg-white rounded-sm shadow-lg mb-4">
      {image && (
        <div className="relative w-full h-56 overflow-hidden">
          <img
            className="w-full h-full object-cover"
            src={`/dA/${inode}`}
            alt="Activity Image"
          />
        </div>
      )}
      <div className="px-6 py-4">
        <p className="mb-2 text-xl font-bold">{title}</p>
        <p className="text-base line-clamp-3">{description}</p>
      </div>
      <div className="px-6 pt-4 pb-2">
        <a
          href={`/activities/${urlTitle || "#"}`}
          className="inline-block px-4 py-2 font-bold rounded-full bg-blue-500 hover:bg-blue-700 text-white"
        >
          Link to detail →
        </a>
      </div>
    </article>
  );
}

export default Activity;

// examples/angular-ssr/src/app/dotcms/components/activity/activity.component.ts
import { NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { Activity } from '../../types/contentlet.model';



@Component({
  selector: 'app-activity',
  imports: [RouterLink, NgOptimizedImage],
  template: ` <article
    class="overflow-hidden p-4 bg-white rounded-sm shadow-lg my-2"
  >
    @if (contentlet().inode; as inode) {
      <div class="relative w-full h-56 overflow-hidden">
        <img
          class="object-cover w-full h-full"
          [ngSrc]="inode"
          fill
          alt="Activity Image"
        />
      </div>
    }
    <div class="px-6 py-4">
      <p class="mb-2 text-xl font-bold">{{ contentlet().title }}</p>
      <p class="text-base line-clamp-3">{{ contentlet().description }}</p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <a
        [routerLink]="'/activities/' + contentlet().urlTitle || '#'"
        class="inline-block px-4 py-2 font-bold text-white bg-red-400 rounded-full hover:bg-red-500"
      >
        Link to detail →
      </a>
    </div>
  </article>`,
  styleUrl: './activity.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ActivityComponent {
  contentlet = input.required<Activity>();
}
