// core-web/libs/sdk/angular/src/lib/components/dotcms-layout-body/components/column/column.component.ts
import { ChangeDetectionStrategy, Component, HostBinding, OnChanges, input } from '@angular/core';

import { DotPageAssetLayoutColumn } from '@dotcms/types';
import { combineClasses, getColumnPositionClasses } from '@dotcms/uve/internal';

import { ContainerComponent } from '../container/container.component';
/**
 * This component renders a column with all its content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @internal
 */
@Component({
    selector: 'dotcms-column',
    imports: [ContainerComponent],
    template: `
        <div [class]="column().styleClass" data-testid="dotcms-column">
            @for (container of column().containers; track $index) {
                <dotcms-container [container]="container" />
            }
        </div>
    `,
    styleUrl: './column.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ColumnComponent implements OnChanges {
    /**
     * The column data to be rendered
     */
    readonly column = input.required<DotPageAssetLayoutColumn>();

    @HostBinding('class') customClasses = '';

    ngOnChanges() {
        const positionClasses = getColumnPositionClasses(this.column());

        this.customClasses = combineClasses([positionClasses.startClass, positionClasses.endClass]);
    }
}

// core-web/libs/sdk/react/src/lib/components/Column/Column.tsx
import { useContext } from 'react';

import styles from './column.module.css';

import { PageContext } from '../../contexts/PageContext';
import { DotCMSPageContext } from '../../models';
import { combineClasses, getPositionStyleClasses } from '../../utils/utils';
import { Container } from '../Container/Container';

/**
 * Props for Column component to render a column with its containers.
 *
 * @export
 * @interface ColumnProps
 */
export interface ColumnProps {
    readonly column: DotCMSPageContext['pageAsset']['layout']['body']['rows'][0]['columns'][0];
}

/**
 * Renders a Column with its containers using information provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @export
 * @param {ColumnProps} { column }
 * @return {JSX.Element} Rendered column with containers
 */
export function Column({ column }: ColumnProps) {
    const { isInsideEditor } = useContext(PageContext) as DotCMSPageContext;

    const { startClass, endClass } = getPositionStyleClasses(
        column.leftOffset,
        column.width + column.leftOffset
    );

    const combinedClasses = combineClasses([styles[endClass], styles[startClass]]);

    const columnProps = isInsideEditor
        ? {
              'data-dot': 'column',
              'data-testid': 'column'
          }
        : {};

    return (
        <div {...columnProps} className={combinedClasses}>
            <div className={column.styleClass}>
                {column.containers.map((container) => (
                    <Container
                        key={`${container.identifier}-${container.uuid}`}
                        containerRef={container}
                    />
                ))}
            </div>
        </div>
    );
}
