// examples/nextjs/src/components/footer/components/blogs.tsx
import RecommendedCard from "@/components/RecommendedCard";
import type { Blog } from "@/types/content";

interface BlogsProps {
    blogs?: Blog[];
}

export default function Blogs({ blogs }: BlogsProps) {
    if (!blogs?.length) return null;

    return (
        <div className="flex flex-col">
            <h2 className="text-2xl font-bold mb-7 text-white">
                Latest Blog Posts
            </h2>
            <div className="flex flex-col gap-5">
                {blogs.map((blog) => (
                    <RecommendedCard key={blog.identifier} contentlet={blog} />
                ))}
            </div>
        </div>
    );
}

// examples/angular/src/app/components/footer/components/blogs/blogs.component.ts
import { Component, input } from '@angular/core';
import { RecommendedCardComponent } from '../recommended-card/recommended-card.component';
import { Blog } from '../../../../dotcms/types/contentlet.model';

@Component({
  selector: 'app-blogs',
  imports: [RecommendedCardComponent],
  template: ` <div class="flex flex-col">
    <h2 class="mb-7 text-2xl font-bold text-black">Latest Blog Posts</h2>
    <div class="flex flex-col gap-5">
      @for (blog of blogs(); track blog.identifier) {
      <app-recommended-card [contentlet]="blog" />
      }
    </div>
  </div>`,
})
export class BlogsComponent {
  blogs = input<Blog[]>([]);
}
