// examples/astro/src/components/content-types/CalendarEvent.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface Location extends DotCMSBasicContentlet {
  title: string;
  url: string;
  activities?: { title: string; urlMap: string }[];
}

interface CalendarEventProps extends DotCMSBasicContentlet {
  image: string;
  title: string;
  urlMap: string;
  description: string;
  location: Location[];
}

function CalendarEvent({
  image,
  title,
  urlMap,
  description,
  location,
}: CalendarEventProps) {
  const { locations, activities } = extractLocationsAndActivities(location);

  return (
    <div className="relative flex bg-clip-border rounded-xl shadow-md w-full flex-row bg-slate-100">
      <div className="relative w-2/5 m-0 overflow-hidden bg-slate-100 rounded-r-none bg-clip-border rounded-xl shrink-0">
        {image && <img src={`/dA/${image}`} alt={title} />}
      </div>
      <div className="p-6">
        <h4 className="block mb-2 text-2xl antialiased font-semibold leading-snug tracking-normal text-blue-gray-900">
          {title}
        </h4>
        {!!locations.length && !!locations[0]?.title && (
          <div className="block mb-2 text-base antialiased leading-snug tracking-normal text-blue-gray-900 break-all">
            <span className="cursor-auto select-none font-semibold underline">
              Locations:
            </span>
            &nbsp;
            {locations.map(({ title, url }, index) => {
              return (
                <a key={index} href={url ?? ""}>
                  <span className="bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-yellow-900 dark:text-yellow-300">
                    {title}
                  </span>
                </a>
              );
            })}
          </div>
        )}
        {!!activities.length && !!activities[0]?.title && (
          <div className="block mb-2 text-base antialiased leading-snug tracking-normal text-blue-gray-900 break-all">
            <span className="cursor-auto select-none font-semibold underline">
              Activities:
            </span>
            &nbsp;
            {activities.slice(0, 3).map(({ title, urlMap }, index) => {
              return (
                <a key={index} href={urlMap ?? ""}>
                  <span className="bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-sm dark:bg-indigo-900 dark:text-indigo-300">
                    {title}
                  </span>
                </a>
              );
            })}
          </div>
        )}
        <div
          className="block mb-8 text-base antialiased font-normal leading-relaxed line-clamp-3"
          dangerouslySetInnerHTML={{ __html: description }}
        />
        <a href={urlMap}>
          <button className="flex items-center gap-2 px-6 py-3 text-xs font-bold text-center uppercase align-middle transition-all rounded-lg select-none disabled:opacity-50 disabled:shadow-none disabled:pointer-events-none hover:bg-gray-900/10 active:bg-gray-900/20">
            Learn More
          </button>
        </a>
      </div>
    </div>
  );
}

// Define a type for the accumulator
interface LocationsAndActivities {
  locations: Location[];
  activities: { title: string; urlMap: string }[];
}

function extractLocationsAndActivities(
  contentlet: Location[],
): LocationsAndActivities {
  const initialValue: LocationsAndActivities = {
    locations: [],
    activities: [],
  };

  return (
    contentlet?.reduce<LocationsAndActivities>(
      (acc, { activities, ...location }) => {
        if (activities) {
          acc.activities = acc.activities.concat(activities);
        }
        acc.locations.push(location);

        return acc;
      },
      initialValue,
    ) ?? initialValue
  );
}

export default CalendarEvent;

// examples/vuejs/src/components/content-types/CalendarEvent.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { DotCMSImage } from '@/types/content';
import { imageLoader } from '@/utils/imageLoader';

interface CalendarActivity {
    title?: string;
    urlMap?: string;
}

interface CalendarLocation {
    title?: string;
    url?: string;
    activities?: CalendarActivity[];
}

const props = defineProps<{
    image?: DotCMSImage;
    title?: string;
    urlMap: string;
    description?: string;
    location?: CalendarLocation[];
}>();

const extracted = computed(() => {
    const locations: Omit<CalendarLocation, 'activities'>[] = [];
    let activities: CalendarActivity[] = [];

    (props.location ?? []).forEach(({ activities: acts, ...location }) => {
        activities = activities.concat(acts ?? []);
        locations.push(location);
    });

    return { locations, activities };
});

const imageSrc = computed(() =>
    props.image?.identifier ? imageLoader(props.image.identifier, 800) : ''
);
</script>

<template>
    <article
        class="flex w-full flex-col overflow-hidden rounded-2xl border border-line bg-bg shadow-sm sm:flex-row">
        <div class="relative h-56 shrink-0 bg-surface sm:h-auto sm:w-2/5">
            <img
                v-if="imageSrc"
                :src="imageSrc"
                :alt="title ?? ''"
                class="absolute inset-0 h-full w-full object-cover" />
        </div>
        <div class="flex flex-col gap-4 p-6 sm:p-8">
            <h3 class="font-display text-2xl font-semibold leading-snug text-ink">{{ title }}</h3>

            <div
                v-if="extracted.locations.length && extracted.locations[0]?.title"
                class="flex flex-wrap items-center gap-2">
                <span class="text-sm font-semibold text-muted">Locations</span>
                <a
                    v-for="(loc, index) in extracted.locations"
                    :key="index"
                    :href="loc.url ?? ''"
                    class="rounded-full bg-primary-tint px-2.5 py-0.5 text-xs font-medium text-primary transition-colors hover:bg-primary hover:text-bg">
                    {{ loc.title }}
                </a>
            </div>

            <div
                v-if="extracted.activities.length && extracted.activities[0]?.title"
                class="flex flex-wrap items-center gap-2">
                <span class="text-sm font-semibold text-muted">Activities</span>
                <a
                    v-for="(act, index) in extracted.activities.slice(0, 3)"
                    :key="index"
                    :href="act.urlMap ?? ''"
                    class="rounded-full bg-surface px-2.5 py-0.5 text-xs font-medium text-ink transition-colors hover:bg-surface-2">
                    {{ act.title }}
                </a>
            </div>

            <!-- eslint-disable-next-line vue/no-v-html -- renders CMS-authored copy -->
            <div class="line-clamp-3 leading-relaxed text-muted" v-html="description ?? ''" />

            <a
                :href="urlMap"
                class="mt-1 inline-flex w-fit items-center gap-1.5 font-semibold text-primary transition-colors hover:text-primary-deep">
                Learn more
                <span aria-hidden="true">→</span>
            </a>
        </div>
    </article>
</template>
