// examples/astro/src/react/content-types/Empty.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

export function CustomNoComponent({ contentType }: DotCMSBasicContentlet) {
    return (
        <div className="relative w-full bg-gray-200 h-12 flex justify-center items-center overflow-hidden">
            Dont have a component for this&nbsp;<strong>{contentType}</strong>.
        </div>
    );
}

// examples/vuejs/src/components/content-types/Empty.vue
<script setup lang="ts">
/** Fallback (`CustomNoComponent`) rendered when no component maps to a content type. */
defineProps<{ contentType?: string }>();
</script>

<template>
    <div
        class="relative w-full bg-gray-200 h-12 flex justify-center items-center overflow-hidden">
        Don't have a component for this&nbsp;<strong>{{ contentType }}</strong>.
    </div>
</template>
