// examples/nextjs/src/components/content-types/VtlInclude.tsx
"use client";

import { useIsEditMode } from "@/hooks/useIsEditMode";
import DestinationListing from "../DestinationListing";

import type { Destination } from "@/types/content";

interface VtlIncludeProps {
    componentType?: string;
    widgetCodeJSON?: {
        destinations?: Destination[];
    };
}

// Learn more about widgetCodeJSON here: https://dev.dotcms.com/docs/scripting-api#ResponseJSON
export default function VtlInclude({ componentType, widgetCodeJSON }: VtlIncludeProps) {
    const isEditMode = useIsEditMode();

    if (componentType === "destinationListing") {
        return <DestinationListing {...widgetCodeJSON} />;
    }

    if (isEditMode) {
        return (
            <div className="bg-blue-100 p-4">
                <h4>
                    No Component Type: {componentType || "generic"} Found for
                    VTL Include
                </h4>
            </div>
        );
    }

    return null;
}

// examples/vuejs/src/components/content-types/VtlInclude.vue
<script setup lang="ts">
import DestinationListing from '@/components/DestinationListing.vue';
import { useIsEditMode } from '@/composables/useIsEditMode';
import type { Destination } from '@/types/content';

/**
 * Renders VTL-scripted widgets by `componentType`. See:
 * https://dev.dotcms.com/docs/scripting-api#ResponseJSON
 */
const props = defineProps<{
    componentType?: string;
    widgetCodeJSON?: { destinations?: Destination[] };
}>();

const isEditMode = useIsEditMode();
</script>

<template>
    <DestinationListing
        v-if="componentType === 'destinationListing'"
        :destinations="widgetCodeJSON?.destinations" />
    <div v-else-if="isEditMode" class="bg-blue-100 p-4">
        <h4>No Component Type: {{ componentType || 'generic' }} Found for VTL Include</h4>
    </div>
</template>
