// examples/astro/src/components/content-types/VtlInclude.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";
import { useIsEditMode } from "@/hooks";
import { DestinationListing, type Destination } from "../ui";

interface VtlIncludeProps extends DotCMSBasicContentlet {
  componentType: string;
  widgetCodeJSON: {
    destinations: Destination[];
  };
}
export default function VtlInclude({
  componentType,
  widgetCodeJSON,
}: VtlIncludeProps) {
  const isEditMode = useIsEditMode();

  if (componentType === "destinationListing") {
    return <DestinationListing destinations={widgetCodeJSON.destinations} />;
  }

  if (isEditMode) {
    return (
      <div className="bg-blue-100 p-4">
        <h4>
          No Component Type: {componentType || "generic"} Found for VTL Include
        </h4>
      </div>
    );
  }

  return null;
}

// examples/vuejs/src/components/content-types/VtlInclude.vue
<script setup lang="ts">
import DestinationListing from '@/components/DestinationListing.vue';
import { useIsEditMode } from '@/composables/useIsEditMode';
import type { Destination } from '@/types/content';

/**
 * Renders VTL-scripted widgets by `componentType`. See:
 * https://dev.dotcms.com/docs/scripting-api#ResponseJSON
 */
const props = defineProps<{
    componentType?: string;
    widgetCodeJSON?: { destinations?: Destination[] };
}>();

const isEditMode = useIsEditMode();
</script>

<template>
    <DestinationListing
        v-if="componentType === 'destinationListing'"
        :destinations="widgetCodeJSON?.destinations" />
    <div v-else-if="isEditMode" class="bg-blue-100 p-4">
        <h4>No Component Type: {{ componentType || 'generic' }} Found for VTL Include</h4>
    </div>
</template>
