// examples/astro/src/components/content-types/CategoryFilter.tsx
import type { DotCMSBasicContentlet } from "@dotcms/types";

interface CategoryFilterProps extends DotCMSBasicContentlet {
  widgetCodeJSON: { categories: { title: string; url: string }[] };
}
export default function CategoryFilter({
  widgetCodeJSON,
}: CategoryFilterProps) {
  const categories = widgetCodeJSON.categories;

  if (!categories) {
    console.warn("No categories found in CategoryFilter");

    return null;
  }

  return (
    <div className="bg-white rounded-lg shadow-sm p-4">
      <h3 className="text-lg font-medium text-gray-900 mb-4">Categories</h3>
      <div className="space-y-2">
        {categories?.map((category) => (
          <CategoryItem
            key={category.url}
            title={category.title}
            url={category.url}
          />
        ))}
      </div>
    </div>
  );
}

function CategoryItem({ title, url }: { title: string; url: string }) {
  return (
    <div className="border-b border-gray-100 pb-2">
      <div className="flex items-center justify-between">
        <a
          href={url}
          className="text-blue-600 hover:text-blue-800 transition-colors duration-200 py-1 block"
        >
          {title}
        </a>
      </div>
    </div>
  );
}

// examples/angular/src/app/dotcms/components/category-filter/category-filter.component.ts
import { Component, computed, input, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink } from '@angular/router';

import { CategoryFilter } from '../../types/contentlet.model';

@Component({
  selector: 'app-category-filter',
  imports: [RouterLink],
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `
    @if (hasCategories()) {
      <div class="bg-white rounded-lg shadow-sm p-4">
        <h3 class="text-lg font-medium text-gray-900 mb-4">Categories</h3>
        <div class="space-y-2">
          @for (category of categories(); track category.url) {
            <div class="border-b border-gray-100 pb-2">
              <div class="flex items-center justify-between">
                <a
                  [routerLink]="category.url"
                  class="text-red-500 hover:text-red-600 transition-colors duration-200 py-1 block"
                >
                  {{ category.title }}
                </a>
              </div>
            </div>
          }
        </div>
      </div>
    }
  `,
})
export class CategoryFilterComponent {
  contentlet = input.required<CategoryFilter>();

  categories = computed(
    () => this.contentlet().widgetCodeJSON?.categories || [],
  );
  hasCategories = computed(
    () => this.categories() && this.categories().length > 0,
  );
}
