// examples/angular/src/app/pages/content-types/empty/empty.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-empty',
  standalone: true,
  template: ` <div class="relative w-full bg-gray-200 h-12 flex justify-center items-center overflow-hidden">Dont have a component for this contentlet.</div> `,
  styles: '',
})
export class EmptyComponent {}

<p>empty works!</p>

// examples/nextjs/src/components/content-types/Empty.tsx
interface CustomNoComponentProps {
    contentType?: string;
}

export function CustomNoComponent({ contentType }: CustomNoComponentProps) {
    return (
        <div className="relative w-full bg-gray-200 h-12 flex justify-center items-center overflow-hidden">
            Dont have a component for this&nbsp;<strong>{contentType}</strong>.
        </div>
    );
}
