// examples/vuejs/src/components/content-types/SimpleWidget.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue';

import { useIsEditMode } from '@/composables/useIsEditMode';

const TRAVEL_BOT_KEY = '908b8a434ad7e539632b8db57f2967c0';
const DESTINATIONS = [
    'Amalfi Coast, Italy',
    'Kyoto, Japan',
    'Patagonia, Chile',
    'Reykjavík, Iceland',
    'Queenstown, New Zealand'
];

const props = defineProps<{ widgetTitle?: string; identifier?: string; code?: string }>();

const isEditMode = useIsEditMode();
const baseId = useId();
const submitted = ref(false);

const isTravelBot = computed(() => props.identifier === TRAVEL_BOT_KEY);
const isBooking = computed(() => props.widgetTitle === 'Booking Date Selector');
</script>

<template>
    <!-- TravelBot promo -->
    <div
        v-if="isTravelBot"
        class="mx-auto my-6 max-w-lg rounded-2xl border border-line bg-bg p-8 text-center">
        <h2 class="font-display text-2xl font-semibold text-ink">Welcome to TravelBot</h2>
        <p class="mt-4 text-muted">
            TravelBot is built with <span class="font-medium text-ink">dotAI</span>, the dotCMS
            suite of AI features.
        </p>
        <p class="mt-2 text-muted">Configure the dotAI App to enable dotAI and TravelBot.</p>
    </div>

    <!-- Booking date selector -->
    <section
        v-else-if="isBooking && submitted"
        class="mx-auto max-w-2xl rounded-2xl bg-primary-deep p-8 text-center text-bg sm:p-10">
        <h3 class="font-display text-2xl font-semibold">Your trip is on hold</h3>
        <p class="mx-auto mt-3 max-w-md text-bg/80">
            This is a demo, so nothing was booked. In a real site this would check availability and
            take you to checkout.
        </p>
        <button
            type="button"
            class="mt-6 inline-flex items-center gap-1.5 rounded-full bg-accent px-6 py-3 font-semibold text-bg transition-transform duration-300 ease-(--ease-out-quart) hover:-translate-y-0.5"
            @click="submitted = false">
            Start over
        </button>
    </section>

    <section v-else-if="isBooking" class="rounded-2xl bg-surface p-6 sm:p-8">
        <div class="mb-6 flex flex-col gap-2">
            <span class="eyebrow">Plan your trip</span>
            <h3 class="font-display text-h3 font-semibold text-ink">Check availability</h3>
        </div>

        <form class="flex flex-wrap items-end gap-4" @submit.prevent="submitted = true">
            <div class="min-w-52 flex-[2]">
                <label
                    :for="`${baseId}-dest`"
                    class="mb-1.5 block text-sm font-medium text-ink">
                    Destination
                </label>
                <select
                    :id="`${baseId}-dest`"
                    required
                    class="w-full appearance-none rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30">
                    <option value="" disabled selected>Where are you headed?</option>
                    <option v-for="d in DESTINATIONS" :key="d" :value="d">{{ d }}</option>
                </select>
            </div>

            <div class="min-w-36 flex-1">
                <label :for="`${baseId}-in`" class="mb-1.5 block text-sm font-medium text-ink">
                    Check in
                </label>
                <input
                    :id="`${baseId}-in`"
                    type="date"
                    required
                    class="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30" />
            </div>

            <div class="min-w-36 flex-1">
                <label :for="`${baseId}-out`" class="mb-1.5 block text-sm font-medium text-ink">
                    Check out
                </label>
                <input
                    :id="`${baseId}-out`"
                    type="date"
                    required
                    class="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30" />
            </div>

            <div class="min-w-24 flex-1">
                <label
                    :for="`${baseId}-guests`"
                    class="mb-1.5 block text-sm font-medium text-ink">
                    Travelers
                </label>
                <input
                    :id="`${baseId}-guests`"
                    type="number"
                    :min="1"
                    :max="12"
                    :value="2"
                    class="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30" />
            </div>

            <button
                type="submit"
                class="inline-flex h-[50px] shrink-0 items-center justify-center gap-2 rounded-full bg-primary px-6 font-semibold text-bg transition-colors hover:bg-primary-deep">
                Search
                <span aria-hidden="true">→</span>
            </button>
        </form>
    </section>

    <!-- Edit-mode fallback -->
    <div
        v-else-if="isEditMode"
        role="alert"
        class="rounded-xl border border-line bg-surface p-4 text-sm text-muted">
        <h4 class="font-medium text-ink">Simple Widget: {{ widgetTitle }}</h4>
    </div>
</template>

// examples/nextjs/src/components/content-types/SimpleWidget.tsx
"use client";

import { useId, useState } from "react";

import { useIsEditMode } from "@/hooks/useIsEditMode";

const TRAVEL_BOT_KEY = "908b8a434ad7e539632b8db57f2967c0";

interface SimpleWidgetProps {
    widgetTitle?: string;
    identifier?: string;
    code?: string;
}

export default function SimpleWidget(props: SimpleWidgetProps) {
    const { widgetTitle, identifier } = props;
    const isEditMode = useIsEditMode();

    if (TRAVEL_BOT_KEY == identifier) {
        return (
            <div className="mx-auto my-6 max-w-lg rounded-2xl border border-line bg-bg p-8 text-center">
                <h2 className="font-display text-2xl font-semibold text-ink">
                    Welcome to TravelBot
                </h2>
                <p className="mt-4 text-muted">
                    TravelBot is built with <span className="font-medium text-ink">dotAI</span>,
                    the dotCMS suite of AI features.
                </p>
                <p className="mt-2 text-muted">
                    Configure the dotAI App to enable dotAI and TravelBot.
                </p>
            </div>
        );
    }

    if (widgetTitle === "Booking Date Selector") {
        return <BookingDateSelector />;
    }

    if (isEditMode) {
        return (
            <div
                role="alert"
                className="rounded-xl border border-line bg-surface p-4 text-sm text-muted"
            >
                <h4 className="font-medium text-ink">Simple Widget: {widgetTitle}</h4>
            </div>
        );
    }

    return null;
}

const DESTINATIONS = [
    "Amalfi Coast, Italy",
    "Kyoto, Japan",
    "Patagonia, Chile",
    "Reykjavík, Iceland",
    "Queenstown, New Zealand",
];

function BookingDateSelector() {
    const baseId = useId();
    const [submitted, setSubmitted] = useState(false);

    if (submitted) {
        return (
            <section className="mx-auto max-w-2xl rounded-2xl bg-primary-deep p-8 text-center text-bg sm:p-10">
                <h3 className="font-display text-2xl font-semibold">
                    Your trip is on hold
                </h3>
                <p className="mx-auto mt-3 max-w-md text-bg/80">
                    This is a demo, so nothing was booked. In a real site this would
                    check availability and take you to checkout.
                </p>
                <button
                    type="button"
                    onClick={() => setSubmitted(false)}
                    className="mt-6 inline-flex items-center gap-1.5 rounded-full bg-accent px-6 py-3 font-semibold text-bg transition-transform duration-300 ease-(--ease-out-quart) hover:-translate-y-0.5"
                >
                    Start over
                </button>
            </section>
        );
    }

    return (
        <section className="rounded-2xl bg-surface p-6 sm:p-8">
            <div className="mb-6 flex flex-col gap-2">
                <span className="eyebrow">Plan your trip</span>
                <h3 className="font-display text-h3 font-semibold text-ink">
                    Check availability
                </h3>
            </div>

            <form
                onSubmit={(e) => {
                    e.preventDefault();
                    setSubmitted(true);
                }}
                className="flex flex-wrap items-end gap-4"
            >
                <Field className="min-w-52 flex-[2]" label="Destination" htmlFor={`${baseId}-dest`}>
                    <select
                        id={`${baseId}-dest`}
                        name="destination"
                        required
                        defaultValue=""
                        className="w-full appearance-none rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30"
                    >
                        <option value="" disabled>
                            Where are you headed?
                        </option>
                        {DESTINATIONS.map((d) => (
                            <option key={d} value={d}>
                                {d}
                            </option>
                        ))}
                    </select>
                </Field>

                <Field className="min-w-36 flex-1" label="Check in" htmlFor={`${baseId}-in`}>
                    <input
                        id={`${baseId}-in`}
                        name="checkIn"
                        type="date"
                        required
                        className="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30"
                    />
                </Field>

                <Field className="min-w-36 flex-1" label="Check out" htmlFor={`${baseId}-out`}>
                    <input
                        id={`${baseId}-out`}
                        name="checkOut"
                        type="date"
                        required
                        className="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30"
                    />
                </Field>

                <Field className="min-w-24 flex-1" label="Travelers" htmlFor={`${baseId}-guests`}>
                    <input
                        id={`${baseId}-guests`}
                        name="guests"
                        type="number"
                        min={1}
                        max={12}
                        defaultValue={2}
                        className="w-full rounded-xl border border-line bg-bg px-4 py-3 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30"
                    />
                </Field>

                <button
                    type="submit"
                    className="inline-flex h-[50px] shrink-0 items-center justify-center gap-2 rounded-full bg-primary px-6 font-semibold text-bg transition-colors hover:bg-primary-deep"
                >
                    Search
                    <span aria-hidden="true">→</span>
                </button>
            </form>
        </section>
    );
}

function Field({
    label,
    htmlFor,
    className,
    children,
}: {
    label: string;
    htmlFor: string;
    className?: string;
    children: React.ReactNode;
}) {
    return (
        <div className={className}>
            <label
                htmlFor={htmlFor}
                className="mb-1.5 block text-sm font-medium text-ink"
            >
                {label}
            </label>
            {children}
        </div>
    );
}
