// core-web/libs/sdk/react/src/lib/components/column/column.tsx
import styles from './column.module.css';

import { ColumnModel } from '../../types/page.model';
import Container from '../container/container';

/* eslint-disable-next-line */
interface ColumnProps {
    column: ColumnModel;
}

export function Column({ column }: ColumnProps) {
    const widthClassMap: Record<number, string> = {
        1: 'col-span-1',
        2: 'col-span-2',
        3: 'col-span-3',
        4: 'col-span-4',
        5: 'col-span-5',
        6: 'col-span-6',
        7: 'col-span-7',
        8: 'col-span-8',
        9: 'col-span-9',
        10: 'col-span-10',
        11: 'col-span-11',
        12: 'col-span-12',
    };

    const statrClassMap: Record<number, string> = {
        1: 'col-start-1',
        2: 'col-start-2',
        3: 'col-start-3',
        4: 'col-start-4',
        5: 'col-start-5',
        6: 'col-start-6',
        7: 'col-start-7',
        8: 'col-start-8',
        9: 'col-start-9',
        10: 'col-start-10',
        11: 'col-start-11',
        12: 'col-start-12',
    };

    const widthClass = widthClassMap[column.width];
    const startClass = statrClassMap[column.leftOffset];

    return (
        <div
            data-dot="column"
            className={`${styles[widthClass]} ${styles[startClass]}`}
        >
            {column.containers.map((container) => (
                <Container
                    key={`${container.identifier}-${container.uuid}`}
                    containerRef={container}
                />
            ))}
        </div>
    );
}

export default Column;

// core-web/libs/sdk/vue/src/lib/components/Column/Column.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

import type { DotPageAssetLayoutColumn } from '@dotcms/types';

import Container from '../Container/Container.vue';

/**
 * @internal
 * Renders a single column of the 12-column grid. Position is derived from the
 * column's `leftOffset`/`width` — the same values the React SDK turns into
 * `col-start-*`/`col-end-*` classes, applied here as inline grid styles.
 */
const props = defineProps<{ column: DotPageAssetLayoutColumn }>();

const gridStyle = computed<CSSProperties>(() => ({
    gridColumnStart: props.column.leftOffset,
    gridColumnEnd: props.column.leftOffset + props.column.width
}));
</script>

<template>
    <div data-dot="column" :style="gridStyle">
        <div :class="column.styleClass">
            <Container
                v-for="container in column.containers"
                :key="`${container.identifier}-${container.uuid}`"
                :container="container" />
        </div>
    </div>
</template>
