// core-web/libs/sdk/react/src/lib/next/components/Container/Container.tsx
import { useContext, useRef } from 'react';
import { isInsideEditor } from '@dotcms/client';

import { DotCMSRenderContext, DotCMSRenderContextI } from '../../contexts/DotCMSRenderContext';
import { DotCMSColumnContainer, DotCMSContentlet } from '../../types';
import { getContainersData } from '../../utils/utils';
import { useCheckVisibleContent } from '../../hooks/useCheckHaveContent';

type ContainerProps = {
    container: DotCMSColumnContainer;
};

/**
 * Renders a Container with its content using information provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @export
 * @param {ContainerProps} { containerRef }
 * @return {JSX.Element} Rendered container with content
 */
export function Container({ container }: ContainerProps) {
    const { identifier, uuid } = container;
    const { dotCMSPageAsset, customComponents } = useContext(
        DotCMSRenderContext
    ) as DotCMSRenderContextI;

    const { acceptTypes, contentlets, maxContentlets, variantId, path } = getContainersData(
        dotCMSPageAsset.containers,
        container
    );

    const containerData = JSON.stringify({
        uuid,
        variantId,
        acceptTypes,
        maxContentlets,
        identifier: path ?? identifier
    }); // Get Container

    const isEmpty = contentlets.length === 0;
    const emptyContainerStyle = {
        width: '100%',
        backgroundColor: '#ECF0FD',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#030E32',
        height: '10rem'
    };

    return (
        <div
            data-testid="dot-container"
            data-dot-object="container"
            data-dot-accept-types={acceptTypes}
            data-dot-identifier={path ?? identifier}
            data-max-contentlets={maxContentlets}
            data-dot-uuid={uuid}
            style={isEmpty ? emptyContainerStyle : {}}>
            {isEmpty
                ? 'This container is empty.'
                : contentlets.map((contentlet: DotCMSContentlet) => (
                      <ComponentRender
                          key={contentlet.identifier}
                          contentlet={contentlet}
                          components={customComponents}
                          container={containerData}
                      />
                  ))}
        </div>
    );
}

// MOVE TO ANOTHER FILE
function ComponentRender({ contentlet, container, components }: any) {
    const ref = useRef<HTMLDivElement | null>(null);
    const haveContent = useCheckVisibleContent(ref);

    const ContentTypeComponent = components[contentlet?.contentType];
    const DefaultComponent = components['CustomNoComponent'] || NoComponent;
    const FallbackComponent = true || isInsideEditor() ? DefaultComponent : EmptyContent;

    const Component = ContentTypeComponent || FallbackComponent;

    return (
        <div
            data-testid="dot-contentlet"
            data-dot-object="contentlet"
            data-dot-identifier={contentlet?.identifier}
            data-dot-basetype={contentlet?.baseType}
            data-dot-title={contentlet?.widgetTitle || contentlet?.title}
            data-dot-inode={contentlet?.inode}
            data-dot-type={contentlet?.contentType}
            data-dot-container={container}
            data-dot-on-number-of-pages={contentlet?.onNumberOfPages}
            key={contentlet?.identifier}
            ref={ref}
            style={{ minHeight: haveContent ? undefined : '4rem' }}>
            <Component {...contentlet} />
        </div>
    );
}

/**
 * Component to render when there is no component for the content type.
 *
 * @param {{ readonly contentType: string }} { contentType }
 * @return {*}
 */
function NoComponent({ contentType }: { readonly contentType: string }) {
    return <div data-testid="no-component">No Component for {contentType}</div>;
}

/**
 * Component to render when there is no content in the container.
 *
 * @return {*}
 */
function EmptyContent() {
    return null;
}

// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/container/container.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    HostBinding,
    inject,
    Input,
    OnChanges,
    signal
} from '@angular/core';

import {
    getContainersData,
    getContentletsInContainer,
    getDotContainerAttributes
} from '@dotcms/uve/internal';
import {
    DotCMSColumnContainer,
    DotCMSContentlet,
    DotContainerAttributes,
    EditableContainerData
} from '@dotcms/uve/types';

import { ContainerNotFoundComponent } from './components/container-not-found/container-not-found.component';
import { EmptyContainerComponent } from './components/empty-container/empty-container.component';

import { DotCMSStore } from '../../../../store/dotcms.store';
import { ContentletComponent } from '../../components/contentlet/contentlet.component';

/**
 * This component renders a container with all its content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @internal
 */
@Component({
    selector: 'dotcms-container',
    standalone: true,
    imports: [ContainerNotFoundComponent, EmptyContainerComponent, ContentletComponent],
    template: `
        @if (!$containerData()) {
            <dotcms-container-not-found [identifier]="container.identifier" />
        } @else if ($isEmpty()) {
            <dotcms-empty-container />
        } @else {
            @for (contentlet of $contentlets(); track contentlet.identifier) {
                <dotcms-contentlet [contentlet]="contentlet" [container]="container.identifier" />
            }
        }
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContainerComponent implements OnChanges {
    /**
     * The container data to be rendered
     */
    @Input({ required: true }) container!: DotCMSColumnContainer;

    #dotCMSStore = inject(DotCMSStore);

    $containerData = signal<EditableContainerData | null>(null);
    $contentlets = signal<DotCMSContentlet[]>([]);
    $isEmpty = computed(() => this.$contentlets().length === 0);
    $dotAttributes = computed<DotContainerAttributes>(() => {
        const containerData = this.$containerData();

        if (!containerData || !this.#dotCMSStore.$isDevMode()) {
            return {} as DotContainerAttributes;
        }

        return getDotContainerAttributes(containerData);
    });

    @HostBinding('attr.data-dot-object') dotObject = 'container';
    @HostBinding('attr.data-dot-accept-types') acceptTypes: string | null = null;
    @HostBinding('attr.data-dot-identifier') identifier: string | null = null;
    @HostBinding('attr.data-max-contentlets') maxContentlets: string | null = null;
    @HostBinding('attr.data-dot-uuid') uuid: string | null = null;

    ngOnChanges() {
        const { page } = this.#dotCMSStore.store ?? {};

        if (!page) {
            return;
        }

        this.$containerData.set(getContainersData(page, this.container));
        this.$contentlets.set(getContentletsInContainer(page, this.container));

        this.acceptTypes = this.$dotAttributes()['data-dot-accept-types'];
        this.identifier = this.$dotAttributes()['data-dot-identifier'];
        this.maxContentlets = this.$dotAttributes()['data-max-contentlets'];
        this.uuid = this.$dotAttributes()['data-dot-uuid'];
    }
}
