// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/GridBlock.tsx
import { BlockEditorNode } from '@dotcms/types';

import { CustomRenderer } from '../../DotCMSBlockEditorRenderer';

interface GridBlockProps {
    node: BlockEditorNode;
    customRenderers?: CustomRenderer;
    blockEditorBlock: React.FC<{
        content: BlockEditorNode[] | undefined;
        customRenderers?: CustomRenderer;
    }>;
}

/**
 * Renders a grid block with two columns using a 12-column grid system.
 *
 * @param node - The grid block node containing column configuration.
 * @param blockEditorBlock - The block editor component for rendering nested content.
 * @param customRenderers - Optional custom renderers for nested blocks.
 */
export const GridBlock = ({ node, blockEditorBlock, customRenderers }: GridBlockProps) => {
    const BlockEditorBlockComponent = blockEditorBlock;
    const rawCols = Array.isArray(node.attrs?.columns) ? node.attrs.columns : [6, 6];
    const cols =
        rawCols.length === 2 &&
        rawCols.every((v: unknown) => typeof v === 'number' && Number.isFinite(v))
            ? rawCols
            : [6, 6];

    return (
        <div
            data-type="gridBlock"
            className="grid-block"
            style={
                {
                    display: 'grid',
                    gridTemplateColumns: 'repeat(12, 1fr)',
                    gap: '1rem'
                } as React.CSSProperties
            }>
            {node.content?.map((column, index) => (
                <div
                    key={`gridColumn-${index}`}
                    data-type="gridColumn"
                    className="grid-block__column"
                    style={{ gridColumn: `span ${cols[index] ?? 6}` }}>
                    <BlockEditorBlockComponent
                        content={column.content}
                        customRenderers={customRenderers}
                    />
                </div>
            ))}
        </div>
    );
};

// core-web/libs/sdk/vue/src/lib/components/DotCMSBlockEditorRenderer/components/blocks/GridBlock.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { BlockEditorNode } from '@dotcms/types';

import BlockEditorBlock from '../BlockEditorBlock.vue';

import type { CustomRenderer } from '../../types';

/** Renders a two-column grid block over a 12-column grid. */
const props = defineProps<{
    node: BlockEditorNode;
    customRenderers?: CustomRenderer;
    isDevMode?: boolean;
}>();

const cols = computed<number[]>(() => {
    const raw = props.node.attrs?.columns;

    return Array.isArray(raw) &&
        raw.length === 2 &&
        raw.every((v: unknown) => typeof v === 'number' && Number.isFinite(v))
        ? (raw as number[])
        : [6, 6];
});

const gridStyle = {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: '1rem'
} as const;
</script>

<template>
  <div
    data-type="gridBlock"
    class="grid-block"
    :style="gridStyle"
  >
    <div
      v-for="(column, index) in node.content ?? []"
      :key="`gridColumn-${index}`"
      data-type="gridColumn"
      class="grid-block__column"
      :style="{ gridColumn: `span ${cols[index] ?? 6}` }"
    >
      <BlockEditorBlock
        :content="column.content"
        :custom-renderers="customRenderers"
        :is-dev-mode="isDevMode"
      />
    </div>
  </div>
</template>
