// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/row/row.component.ts
import { ChangeDetectionStrategy, Component, Input, OnChanges, signal } from '@angular/core';

import { combineClasses } from '@dotcms/uve/internal';
import { DotPageAssetLayoutRow } from '@dotcms/uve/types';

import { ColumnComponent } from '../column/column.component';

/**
 * This component renders a row with all its content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @internal
 */
@Component({
    selector: 'dotcms-row',
    standalone: true,
    imports: [ColumnComponent],
    template: `
        <div class="dot-row-container">
            <div [class]="customClasses()" data-dot-object="row" data-testid="dotcms-row">
                @for (column of row.columns; track $index) {
                    <dotcms-column [column]="column" />
                }
            </div>
        </div>
    `,
    styleUrl: './row.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class RowComponent implements OnChanges {
    /**
     * The row data to be rendered
     */
    @Input({ required: true }) row!: DotPageAssetLayoutRow;

    customClasses = signal('');

    ngOnChanges() {
        this.customClasses.set(combineClasses([this.row.styleClass || 'dot-row']));
    }
}

// core-web/libs/sdk/react/src/lib/components/Row/Row.tsx
import { forwardRef, useContext } from 'react';

import styles from './row.module.css';

import { PageContext } from '../../contexts/PageContext';
import { DotCMSPageContext } from '../../models';
import { combineClasses } from '../../utils/utils';
import { Column } from '../Column/Column';

/**
 * Props for the row component
 *
 * @interface RowProps
 *
 */
export interface RowProps {
    /**
     * Row data
     *
     * @type {DotCMSPageContext['layout']['body']['rows'][0]}
     * @memberof RowProps
     */
    row: DotCMSPageContext['pageAsset']['layout']['body']['rows'][0];
}

/**
 * This component renders a row with all it's content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @param {React.ForwardedRef<HTMLDivElement, RowProps>} ref
 * @return {JSX.Element} Rendered rows with columns
 */
export const Row = forwardRef<HTMLDivElement, RowProps>((props: RowProps, ref) => {
    const { isInsideEditor } = useContext<DotCMSPageContext | null>(
        PageContext
    ) as DotCMSPageContext;

    const { row } = props;

    console.log(row.styleClass);

    const rowProps = isInsideEditor ? { 'data-dot': 'row', 'data-testid': 'row', ref } : {};

    return (
        <div className={row.styleClass}>
            <div className="container">
                <div {...rowProps} className={styles.row}>
                    {row.columns.map((column, index) => (
                        <Column key={index} column={column} />
                    ))}
                </div>
            </div>
        </div>
    );
});
