// examples/astro/src/react/shared/contentlets.tsx
import useImageSrc from "../hooks/useImageSrc";
import Contentlet from "./contentlet";

const dateFormatOptions: DateTimeFormatOptions = {
    year: "numeric",
    month: "long",
    day: "numeric",
};

function Contentlets({ contentlets }) {
    return (
        <ul className="flex flex-col gap-7">
            {contentlets.map((contentlet) => (
                <Contentlet contentlet={contentlet} key={contentlet.identifier}>
                    <li className="flex gap-7 min-h-16">
                        <a
                            className="relative min-w-32"
                            href={contentlet.urlMap || contentlet.url}
                        >
                            {contentlet.image && (
                                <img
                                    src={
                                        useImageSrc({
                                            src: contentlet.image?.idPath ?? contentlet.image
                                        })
                                    }
                                    alt={contentlet.urlTitle}
                                    className="object-cover absolute w-full h-full top-0 left-0"
                                />
                            )}
                        </a>
                        <div className="flex flex-col gap-1">
                            <a
                                className="text-sm text-zinc-900 font-bold"
                                href={contentlet.urlMap || contentlet.url}
                            >
                                {contentlet.title}
                            </a>
                            <time className="text-zinc-600">
                                {new Date(
                                    contentlet.modDate
                                ).toLocaleDateString(
                                    "en-US",
                                    dateFormatOptions
                                )}
                            </time>
                        </div>
                    </li>
                </Contentlet>
            ))}
        </ul>
    );
}

export default Contentlets;

// examples/angular/src/app/components/contentlets/contentlets.component.ts
import { Component, Input } from '@angular/core';
import { Contentlet } from '@dotcms/client/src/lib/client/content/shared/types';
import { GenericContentlet } from '../../utils';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-contentlets',
  standalone: true,
  imports: [],
  template: `<ul class="flex flex-col gap-7">
    @for(contentlet of contentlets; track contentlet.identifier) {
    <li class="flex gap-7 min-h-16">
      <a class="min-w-32 relative" [href]="contentlet.urlMap ?? contentlet.url">
        <img
          [src]="getImageUrl(contentlet)"
          [alt]="contentlet.urlTitle ?? contentlet.title"
          class="object-cover absolute w-full h-full inset-0 text-black"
        />
      </a>
      <div class="flex flex-col gap-1">
        <a
          class="text-sm text-zinc-900 font-bold"
          [href]="contentlet.urlMap ?? contentlet.url"
        >
          {{ contentlet.title }}
        </a>
        <time class="text-zinc-600">
          {{ getDateString(contentlet.modDate) }}
        </time>
      </div>
    </li>
    }
  </ul> `,
})
export class ContentletsComponent {
  @Input() contentlets: Contentlet<GenericContentlet>[] = [];

  dateFormatOptions: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  };

  getDateString(date: string): string {
    return new Date(date).toLocaleDateString('en-US', this.dateFormatOptions);
  }

  getImageUrl(contentlet: Contentlet<GenericContentlet>): string {
    const host = environment.dotcmsUrl;
    return `${host}${contentlet.image}?language_id=${
      contentlet.languageId || 1
    }`;
  }
}
