// core-web/libs/dotcms-webcomponents/src/elements/dot-contentlet-thumbnail/dot-contentlet-thumbnail.tsx
import { Component, h, Host, Prop, State } from '@stencil/core';
import { DotContentletItem } from '../../models/dot-contentlet-item.model';

@Component({
    tag: 'dot-contentlet-thumbnail',
    styleUrl: 'dot-contentlet-thumbnail.scss'
})
export class DotContentletThumbnail {
    @Prop({ reflect: true })
    height = '';

    @Prop({ reflect: true })
    width = '';

    @Prop({ reflect: true })
    alt = '';

    @Prop({ reflect: true })
    iconSize = '';

    @Prop({ reflect: true })
    cover = true;

    @Prop()
    contentlet: DotContentletItem;

    @State() renderImage: boolean;

    componentWillLoad() {
        const { hasTitleImage, mimeType } = this.contentlet;
        // Some endpoints return this property as a boolean
        if (typeof hasTitleImage === 'boolean' && hasTitleImage) {
            this.renderImage = hasTitleImage;
        } else {
            this.renderImage =
                hasTitleImage === 'true' ||
                mimeType === 'application/pdf' ||
                this.isVideoContentlet();
        }
    }

    render() {
        const image = this.contentlet && this.cover ? `url(${this.getImageURL()})` : '';

        return (
            <Host>
                {this.isVideoContentlet() ? (
                    <dot-video-thumbnail contentlet={this.contentlet} />
                ) : this.renderImage ? (
                    <div
                        class={`thumbnail ${this.cover && 'cover'}`}
                        style={{ 'background-image': image }}
                    >
                        <img
                            src={this.getImageURL()}
                            alt={this.alt}
                            aria-label={this.alt}
                            onError={() => this.switchToIcon()}
                        />
                    </div>
                ) : (
                    <dot-contentlet-icon
                        icon={this.getIcon()}
                        size={this.iconSize}
                        aria-label={this.alt}
                    />
                )}
            </Host>
        );
    }

    private getImageURL(): string {
        return this.contentlet.mimeType === 'application/pdf'
            ? `/contentAsset/image/${this.contentlet.inode}/${this.contentlet.titleImage}/pdf_page/1/resize_w/250/quality_q/45`
            : `/dA/${this.contentlet.inode}/500w/20q?r=${this.contentlet.modDateMilis}`;
    }

    private switchToIcon(): any {
        this.renderImage = false;
    }

    private getIcon() {
        return this.contentlet?.baseType !== 'FILEASSET'
            ? this.contentlet?.contentTypeIcon
            : this.contentlet?.__icon__;
    }

    private isVideoContentlet() {
        return this.contentlet?.mimeType.includes('video');
    }
}

// core-web/libs/ui/src/lib/components/dot-contentlet-thumbnail/dot-contentlet-thumbnail.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

import { DotCMSContentlet } from '@dotcms/dotcms-models';

import { DotContentletIconComponent } from '../dot-contentlet-icon/dot-contentlet-icon.component';

@Component({
    selector: 'dot-contentlet-thumbnail-ng',
    standalone: true,
    imports: [CommonModule, DotContentletIconComponent],
    templateUrl: './dot-contentlet-thumbnail.component.html',
    styleUrl: './dot-contentlet-thumbnail.component.scss',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DotContentletThumbnailComponent {
    @Input() contentlet: DotCMSContentlet;
    @Input() width = 64;
    @Input() height = 64;
    @Input() showLabel = true;

    /**
     * Get thumbnail URL for the contentlet
     */
    getThumbnailUrl(): string {
        if (!this.contentlet) {
            return '';
        }

        // Handle PDF files
        if (this.contentlet.mimeType === 'application/pdf') {
            return `/contentAsset/image/${this.contentlet.inode}/${
                this.contentlet.titleImage
            }/pdf_page/1/resize_w/250/quality_q/45`;
        }

        // Handle SVG files
        if (this.contentlet.mimeType === 'image/svg+xml') {
            return `/contentAsset/image/${this.contentlet.inode}/asset`;
        }

        // Handle regular images with dA path
        if (this.contentlet.titleImage && this.contentlet.titleImage !== 'TITLE_IMAGE_NOT_FOUND') {
            return `/dA/${this.contentlet.inode}/${this.contentlet.titleImage}/500w/50q`;
        }

        return '';
    }

    /**
     * Get title for the contentlet
     */
    getTitle(): string {
        return this.contentlet?.title || '';
    }

    /**
     * Get icon for the contentlet
     */
    getContentletIcon(): string {
        if (!this.contentlet) {
            return '';
        }

        if (this.contentlet.__icon__) {
            return this.contentlet.__icon__;
        }

        return this.contentlet.contentTypeIcon || '';
    }

    /**
     * Check if thumbnail should display an image or icon
     */
    shouldShowImage(): boolean {
        return !!this.getThumbnailUrl();
    }
}

<div class="dot-contentlet-thumbnail__image" [style.width.px]="width" [style.height.px]="height">
    <img *ngIf="shouldShowImage()" [src]="getThumbnailUrl()" [alt]="getTitle()" />
    <dot-contentlet-icon-ng *ngIf="!shouldShowImage()" [contentlet]="contentlet" [size]="24"></dot-contentlet-icon-ng>
</div>
<div *ngIf="showLabel && getTitle()" class="dot-contentlet-thumbnail__label">
    {{ getTitle() }}
</div>
