// core-web/libs/sdk/angular/next/components/dotcms-layout-body/components/contentlet/contentlet.component.ts
import { AsyncPipe, NgComponentOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    ElementRef,
    inject,
    Input,
    OnChanges,
    HostBinding,
    signal,
    ViewChild
} from '@angular/core';

import { CUSTOM_NO_COMPONENT, getDotContentletAttributes } from '@dotcms/uve/internal';
import { DotCMSContentlet, DotContentletAttributes } from '@dotcms/uve/types';

import { DynamicComponentEntity } from '../../../../models';
import { DotCMSStore } from '../../../../store/dotcms.store';
import { FallbackComponent } from '../fallback-component/fallback-component.component';

/**
 * Contentlet component that renders DotCMS content with development mode support
 *
 * @component
 * @param {DotCMSContentlet} contentlet - The contentlet to be rendered
 * @param {string} container - The container identifier
 */
@Component({
    selector: 'dotcms-contentlet',
    standalone: true,
    imports: [FallbackComponent, AsyncPipe, NgComponentOutlet],
    template: `
        @if ($UserComponent()) {
            <ng-container
                *ngComponentOutlet="
                    $UserComponent() | async;
                    inputs: { contentlet: $contentlet() ?? contentlet }
                " />
        } @else if ($UserNoComponent() && $isDevMode()) {
            <dotcms-fallback-component
                [UserNoComponent]="$UserNoComponent()"
                [contentlet]="$contentlet() ?? contentlet" />
        }
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContentletComponent implements OnChanges {
    @Input({ required: true }) contentlet!: DotCMSContentlet;
    @Input({ required: true }) container!: string;
    @ViewChild('contentletRef') contentletRef!: ElementRef;
    @HostBinding('attr.data-dot-object') dotObject = 'contentlet';

    #dotCMSStore = inject(DotCMSStore);

    $contentlet = signal<DotCMSContentlet | null>(null);
    $UserComponent = signal<DynamicComponentEntity | null>(null);
    $UserNoComponent = signal<DynamicComponentEntity | null>(null);
    $isDevMode = signal(false);
    $haveContent = signal(false);
    $style = computed(() =>
        this.$isDevMode() && this.$haveContent() ? { minHeight: '4rem' } : {}
    );
    $dotAttributes = computed<DotContentletAttributes>(() => {
        const contentlet = this.$contentlet();
        if (!contentlet || !this.$isDevMode()) return {} as DotContentletAttributes;

        return getDotContentletAttributes(contentlet, this.container);
    });

    @HostBinding('attr.data-dot-identifier') identifier: string | null = null;
    @HostBinding('attr.data-dot-basetype') basetype: string | null = null;
    @HostBinding('attr.data-dot-title') title: string | null = null;
    @HostBinding('attr.data-dot-inode') inode: string | null = null;
    @HostBinding('attr.data-dot-type') type: string | null = null;
    @HostBinding('attr.data-dot-container') containerAttribute: string | null = null;
    @HostBinding('attr.data-dot-on-number-of-pages') onNumberOfPages: string | null = null;
    @HostBinding('style') styleAttribute: { [key: string]: unknown } | null = null;

    ngOnChanges() {
        this.$contentlet.set(this.contentlet);
        this.$isDevMode.set(this.#dotCMSStore.isDevMode());
        this.setupComponents();

        this.identifier = this.$dotAttributes()['data-dot-identifier'];
        this.basetype = this.$dotAttributes()['data-dot-basetype'];
        this.title = this.$dotAttributes()['data-dot-title'];
        this.inode = this.$dotAttributes()['data-dot-inode'];
        this.type = this.$dotAttributes()['data-dot-type'];
        this.containerAttribute = this.$dotAttributes()['data-dot-container'];
        this.onNumberOfPages = this.$dotAttributes()['data-dot-on-number-of-pages'];
        this.styleAttribute = this.$style();
    }

    ngAfterViewInit() {
        this.checkContent();
    }

    private setupComponents() {
        const store = this.#dotCMSStore.store;
        if (!store) return;

        if (!store?.components) return;

        this.$UserComponent.set(store.components[this.contentlet?.contentType]);
        this.$UserNoComponent.set(store.components[CUSTOM_NO_COMPONENT]);
    }

    private checkContent() {
        const element = this.contentletRef?.nativeElement;
        if (element) {
            const hasContent = element.getBoundingClientRect().height > 0;
            this.$haveContent.set(hasContent);
        }
    }
}

// core-web/libs/sdk/react/src/lib/next/components/Contentlet/Contentlet.tsx
import { useContext, useRef, useMemo } from 'react';

import { DotCMSPageContext } from '../../contexts/DotCMSPageContext';
import { useCheckVisibleContent } from '../../hooks/useCheckVisibleContent';
import { useIsDevMode } from '../../hooks/useIsDevMode';
import { DotCMSContentlet } from '../../types';
import { getDotContentletAttributes } from '../../utils';
import { FallbackComponent } from '../FallbackComponent/FallbackComponent';

/**
 * Props for the Contentlet component
 * @interface DotCMSContentletRendererProps
 * @property {DotCMSContentlet} contentlet - The contentlet data to be rendered
 * @property {string} container - The container identifier where the contentlet is placed
 */
interface DotCMSContentletRendererProps {
    contentlet: DotCMSContentlet;
    container: string;
}

/**
 * Props for the CustomComponent
 * @interface CustomComponentProps
 * @property {DotCMSContentlet} contentlet - The contentlet data to be rendered
 */
interface CustomComponentProps {
    contentlet: DotCMSContentlet;
}

/**
 * Contentlet component that renders DotCMS content with development mode support
 *
 * @component
 * @param {DotCMSContentletRendererProps} props - Component properties
 * @param {DotCMSContentlet} props.contentlet - The contentlet to be rendered
 * @param {string} props.container - The container identifier
 * @returns {JSX.Element} Rendered contentlet with appropriate wrapper and attributes
 *
 * @example
 * ```tsx
 * <Contentlet
 *   contentlet={myContentlet}
 *   container="container-1"
 * />
 * ```
 */
export function Contentlet({ contentlet, container }: DotCMSContentletRendererProps) {
    const ref = useRef<HTMLDivElement | null>(null);
    const isDevMode = useIsDevMode();
    const haveContent = useCheckVisibleContent(ref);

    const style = useMemo(
        () => (isDevMode ? { minHeight: haveContent ? undefined : '4rem' } : {}),
        [isDevMode, haveContent]
    );
    const dotAttributes = useMemo(
        () => (isDevMode ? getDotContentletAttributes(contentlet, container) : {}),
        [isDevMode, contentlet, container]
    );

    return (
        <div {...dotAttributes} data-dot-object="contentlet" ref={ref} style={style}>
            <CustomComponent contentlet={contentlet} />
        </div>
    );
}

/**
 * Renders a custom component based on the contentlet type or falls back to a default component
 *
 * @component
 * @param {CustomComponentProps} props - Component properties
 * @param {DotCMSContentlet} props.contentlet - The contentlet data to render
 * @returns {JSX.Element} The rendered custom component or fallback component
 *
 * @internal
 */
function CustomComponent({ contentlet }: CustomComponentProps) {
    const { userComponents } = useContext(DotCMSPageContext);
    const UserComponent = userComponents[contentlet?.contentType];

    if (UserComponent) {
        return <UserComponent {...contentlet} />;
    }

    const UserNoComponent = userComponents['CustomNoComponent'];

    return <FallbackComponent UserNoComponent={UserNoComponent} contentlet={contentlet} />;
}
