// examples/angular-ssr/src/app/components/footer/components/destinations/destinations.component.ts
import { Component, input } from '@angular/core';

import { RecommendedCardComponent } from '../recommended-card/recommended-card.component';

import { Destination } from '../../../../dotcms/types/contentlet.model';

@Component({
  selector: 'app-destinations',
  imports: [RecommendedCardComponent],
  template: ` <div class="flex flex-col">
    <h2 class="mb-7 text-2xl font-bold text-black">Popular Destinations</h2>
    <div class="flex flex-col gap-5">
      @for (destination of destinations(); track destination.identifier) {
        <app-recommended-card [contentlet]="destination" />
      }
    </div>
  </div>`,
})
export class DestinationsComponent {
  destinations = input<Destination[]>([]);
}

// examples/nextjs-experiments/src/components/footer/components/destinations.tsx
import RecommendedCard from "@/components/RecommendedCard";
import type { Destination } from "@/types/content";

interface DestinationsProps {
    destinations?: Destination[];
}

export default function Destinations({ destinations }: DestinationsProps) {
    if (!destinations?.length) return null;

    return (
        <div className="flex flex-col">
            <h2 className="mb-6 text-sm font-semibold uppercase tracking-wider text-bg/60">
                Popular destinations
            </h2>
            <div className="flex flex-col gap-4">
                {destinations.map((destination) => (
                    <RecommendedCard
                        key={destination.identifier}
                        contentlet={destination}
                    />
                ))}
            </div>
        </div>
    );
}
