// core-web/libs/sdk/react/src/lib/next/components/Row/Row.tsx
import { combineClasses } from '@dotcms/uve/internal';
import { DotPageAssetLayoutRow } from '@dotcms/uve/types';

import styles from './Row.module.css';

import { Column } from '../Column/Column';

/**
 * @internal
 *
 * Props for the Row component
 * @interface DotCMSRowRendererProps
 * @property {DotPageAssetLayoutRow} row - The row data to be rendered
 */
type DotCMSRowRendererProps = {
    row: DotPageAssetLayoutRow;
};
/**
 * This component renders a row with all it's content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @param {React.ForwardedRef<HTMLDivElement, DotCMS>} ref
 * @return {JSX.Element} Rendered rows with columns
 */
export const Row = ({ row }: DotCMSRowRendererProps) => {
    const customRowClass = combineClasses([row.styleClass || '', styles.row]);

    return (
        <div className="dot-row-container">
            <div className={customRowClass} data-dot-object={'row'}>
                {row.columns.map((column, index) => (
                    <Column key={index} column={column} />
                ))}
            </div>
        </div>
    );
};

// core-web/libs/sdk/angular/src/lib/components/dotcms-layout-body/components/row/row.component.ts
import { ChangeDetectionStrategy, Component, Input, OnChanges, signal } from '@angular/core';

import { DotPageAssetLayoutRow } from '@dotcms/types';
import { combineClasses } from '@dotcms/uve/internal';

import { ColumnComponent } from '../column/column.component';

/**
 * @description This component renders a row with all its content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @internal
 * @class RowComponent
 */
@Component({
    selector: 'dotcms-row',
    imports: [ColumnComponent],
    template: `
        <div class="dot-row-container">
            <div [class]="customClasses()" data-dot-object="row" data-testid="dotcms-row">
                @for (column of row.columns; track $index) {
                    <dotcms-column [column]="column" />
                }
            </div>
        </div>
    `,
    styleUrl: './row.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class RowComponent implements OnChanges {
    /**
     * The row data to be rendered
     */
    @Input({ required: true }) row!: DotPageAssetLayoutRow;

    customClasses = signal('');

    ngOnChanges() {
        this.customClasses.set(combineClasses([this.row.styleClass || 'dot-row']));
    }
}
