// core-web/libs/sdk/vue/src/lib/components/Row/Row.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { DotPageAssetLayoutRow } from '@dotcms/types';
import { combineClasses, DOT_SECTION_ID_PREFIX } from '@dotcms/uve/internal';

import Column from '../Column/Column.vue';

/**
 * @internal
 * Renders a layout row and its columns. The `id` is the section anchor the
 * editor scrolls to; the inner grid spans 12 columns.
 */
const props = defineProps<{
    row: DotPageAssetLayoutRow;
    /** 1-based section index used as the scroll-to-section anchor id. */
    index: number;
}>();

const rowClass = computed(() => combineClasses(['dot-row-container', props.row.styleClass || '']));
const sectionId = computed(() => `${DOT_SECTION_ID_PREFIX}${props.index}`);
</script>

<template>
  <div
    :id="sectionId"
    :class="rowClass"
  >
    <div
      class="dotcms-row"
      data-dot-object="row"
    >
      <Column
        v-for="(column, i) in row.columns"
        :key="i"
        :column="column"
      />
    </div>
  </div>
</template>

<style scoped>
.dotcms-row {
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    gap: 1rem;
}
</style>

// core-web/libs/sdk/react/src/lib/next/components/Row/Row.tsx
import { DotPageAssetLayoutRow } from '@dotcms/types';
import { combineClasses, DOT_SECTION_ID_PREFIX } from '@dotcms/uve/internal';

import styles from './Row.module.css';

import { Column } from '../Column/Column';

/**
 * @internal
 *
 * Props for the Row component
 * @interface DotCMSRowRendererProps
 * @property {DotPageAssetLayoutRow} row - The row data to be rendered
 */
type DotCMSRowRendererProps = {
    row: DotPageAssetLayoutRow;
    /** 1-based section index used as the `id` anchor for editor scroll-to-section. */
    index: number;
};
/**
 * This component renders a row with all it's content using the layout provided by dotCMS Page API.
 *
 * @see {@link https://www.dotcms.com/docs/latest/page-rest-api-layout-as-a-service-laas}
 * @category Components
 * @param {React.ForwardedRef<HTMLDivElement, DotCMS>} ref
 * @return {JSX.Element} Rendered rows with columns
 */
export const Row = ({ row, index }: DotCMSRowRendererProps) => {
    const customRowClass = combineClasses(['dot-row-container', row.styleClass || '']);

    return (
        <div id={`${DOT_SECTION_ID_PREFIX}${index}`} className={customRowClass}>
            <div className={styles.row} data-dot-object={'row'}>
                {row.columns.map((column, index) => (
                    <Column key={index} column={column} />
                ))}
            </div>
        </div>
    );
};
