// examples/vuejs/src/components/content-types/WebPageContent.vue
<script setup lang="ts">
defineProps<{ title?: string; body?: string }>();
</script>

<template>
    <section class="mx-auto w-full max-w-2xl">
        <h2 v-if="title" class="mb-4 font-display text-h2 font-semibold text-ink">{{ title }}</h2>
        <!-- eslint-disable-next-line vue/no-v-html -- renders CMS-authored rich text -->
        <div
            v-if="body"
            class="prose prose-lg max-w-none text-ink prose-headings:font-display prose-a:text-primary hover:prose-a:text-primary-deep"
            v-html="body" />
    </section>
</template>

// examples/nextjs-experiments/src/components/content-types/WebPageContent.tsx
interface WebPageContentProps {
    title?: string;
    body?: string;
}

function WebPageContent({ title, body }: WebPageContentProps) {
    return (
        <section className="mx-auto w-full max-w-2xl">
            {title && (
                <h2 className="mb-4 font-display text-h2 font-semibold text-ink">{title}</h2>
            )}
            {body && (
                <div
                    className="prose prose-lg max-w-none text-ink prose-headings:font-display prose-a:text-primary hover:prose-a:text-primary-deep"
                    dangerouslySetInnerHTML={{ __html: body }}
                />
            )}
        </section>
    );
}

export default WebPageContent;
