// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/audio.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

/**
 * Renders a dotCMS audio block as a native `<audio>` element. Mirrors {@link DotVideoBlock}
 * but without poster/width/height, which are not meaningful for audio.
 */
@Component({
    selector: 'dotcms-block-editor-renderer-audio',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <audio [controls]="true" preload="metadata">
            <source [src]="attrs?.['src']" [type]="attrs?.['mimeType']" />
            Your browser does not support the
            <code>audio</code>
            element.
        </audio>
    `
})
export class DotAudioBlock {
    @Input() attrs!: BlockEditorNode['attrs'];
}

// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Audio.tsx
import { BlockEditorNode } from '@dotcms/types';

interface DotCMSAudioProps {
    src: string;
    mimeType: string;
}

/**
 * Renders an audio component for displaying audio files. Mirrors {@link DotCMSVideo}
 * but without poster/width/height, which are not meaningful for audio.
 *
 * @param props - The properties for the audio component.
 * @returns The rendered audio component.
 */
export const DotCMSAudio = ({ node }: { node: BlockEditorNode }) => {
    const { src, mimeType } = node.attrs as DotCMSAudioProps;

    return (
        <audio controls preload="metadata">
            <source src={src} type={mimeType} />
            Your browser does not support the <code>audio</code> element.
        </audio>
    );
};
