// core-web/libs/sdk/angular/next/components/dotcms-block-editor-renderer/blocks/contentlet.component.ts
import { AsyncPipe, NgComponentOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, Input } from '@angular/core';

import { Contentlet, BlockEditorNode } from '@dotcms/types';

import { DynamicComponentEntity } from '../../../models';
import { CustomRenderer } from '../dotcms-block-editor-renderer.component';

/**
 * Default component for unknown content type
 */
@Component({
    selector: 'dot-default-content',
    template: '<div>Unknown Content Type: {{ contentlet?.contentType }}</div>',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DotDefaultContentBlock {
    @Input() contentlet: Contentlet<unknown> | undefined;
}

/**
 * DotContent component that renders content based on content type
 */
@Component({
    selector: 'dotcms-block-editor-renderer-contentlet',
    standalone: true,
    imports: [NgComponentOutlet, AsyncPipe],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template:
        '<ng-container *ngComponentOutlet="contentComponent | async; inputs: { contentlet: $data() }"></ng-container>'
})
export class DotContentletBlock {
    @Input() customRenderers: CustomRenderer | undefined;
    @Input() attrs: BlockEditorNode['attrs'];

    contentComponent: DynamicComponentEntity | undefined;

    protected readonly $data = computed(() => this.attrs?.['data'] as Contentlet<unknown>);

    ngOnInit() {
        if (!this.$data()) {
            console.error('DotCMSBlockEditorRendererContentlet: No data provided');
        }

        this.contentComponent =
            this.customRenderers?.[this.$data()?.contentType] ??
            import('./contentlet.component').then((m) => m.DotDefaultContentBlock);
    }
}

// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Contentlet.tsx
import { BlockEditorNode } from '@dotcms/types';

import { useIsDevMode } from '../../../../hooks/useIsDevMode';
import { CustomRenderer } from '../../DotCMSBlockEditorRenderer';

interface DotContentProps {
    customRenderers: CustomRenderer;
    node: BlockEditorNode;
}

/**
 * Renders a DotContent component.
 *
 * @param {DotContentProps} props - The props for the DotContent component.
 * @returns {JSX.Element} The rendered DotContent component.
 */
export const DotContent = ({ customRenderers, node }: DotContentProps) => {
    const isDevMode = useIsDevMode();
    const attrs = node?.attrs || {};
    const data = attrs.data;

    if (!data) {
        console.error('DotContent: No data provided');

        return null;
    }

    const contentType = data.contentType || 'Unknown Content Type';
    const Component = customRenderers[contentType];

    if (isDevMode && !Component) {
        return <div>Unknown ContentType: {contentType}</div>;
    }

    return <Component {...node} />;
};
