// core-web/libs/sdk/vue/src/lib/components/DotCMSBlockEditorRenderer/components/blocks/DotContent.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { BlockEditorNode } from '@dotcms/types';

import NoComponentProvided from './NoComponentProvided.vue';

import type { CustomRenderer } from '../../types';

const NO_DATA_MESSAGE =
    '[DotCMSBlockEditorRenderer]: No data provided for Contentlet Block. Try to add a contentlet to the block editor. If the error persists, please contact the DotCMS support team.';

const noMatchingComponentMessage = (contentType: string) =>
    `[DotCMSBlockEditorRenderer]: No matching component found for content type: ${contentType}. Provide a custom renderer for this content type to fix this error.`;

/** Renders an embedded contentlet block via a custom renderer keyed by content type. */
const props = defineProps<{
    node: BlockEditorNode;
    customRenderers?: CustomRenderer;
    isDevMode?: boolean;
}>();

const data = computed(() => props.node.attrs?.data as { contentType?: string } | undefined);
const contentType = computed(() => data.value?.contentType ?? 'Unknown Content Type');
const component = computed(() => props.customRenderers?.[contentType.value]);

const state = computed<'no-data' | 'dev-warning' | 'no-component' | 'render'>(() => {
    if (!data.value) {
        console.error(NO_DATA_MESSAGE);

        return 'no-data';
    }

    if (props.isDevMode && !component.value) {
        return 'dev-warning';
    }

    if (!component.value) {
        console.warn(noMatchingComponentMessage(contentType.value));

        return 'no-component';
    }

    return 'render';
});
</script>

<template>
  <NoComponentProvided
    v-if="state === 'dev-warning'"
    :content-type="contentType"
  />
  <component
    :is="component"
    v-else-if="state === 'render'"
    :node="node"
  />
</template>

// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/DotContent.tsx
import { BlockEditorNode } from '@dotcms/types';

import { NoComponentProvided } from './NoComponentProvided';

import { CustomRenderer } from '../../DotCMSBlockEditorRenderer';

interface DotContentProps {
    customRenderers?: CustomRenderer;
    node: BlockEditorNode;
    isDevMode?: boolean;
}

const DOT_CONTENT_NO_DATA_MESSAGE =
    '[DotCMSBlockEditorRenderer]: No data provided for Contentlet Block. Try to add a contentlet to the block editor. If the error persists, please contact the DotCMS support team.';

const DOT_CONTENT_NO_MATCHING_COMPONENT_MESSAGE = (contentType: string) =>
    `[DotCMSBlockEditorRenderer]: No matching component found for content type: ${contentType}. Provide a custom renderer for this content type to fix this error.`;

/**
 * Renders a DotContent component.
 *
 * @param {DotContentProps} props - The props for the DotContent component.
 * @returns {JSX.Element} The rendered DotContent component.
 */
export const DotContent = ({ customRenderers, node, isDevMode = false }: DotContentProps) => {
    const { attrs = {} } = node;
    const { data } = attrs;

    if (!data) {
        console.error(DOT_CONTENT_NO_DATA_MESSAGE);

        return null;
    }

    const { contentType = 'Unknown Content Type' } = data;
    const Component = customRenderers?.[contentType];

    /* In dev mode, show a helpful message for unknown content types */
    if (isDevMode && !Component) {
        return <NoComponentProvided contentType={contentType} />;
    }

    /* In production, use default component if no matching component found */
    if (!Component) {
        console.warn(DOT_CONTENT_NO_MATCHING_COMPONENT_MESSAGE(contentType));

        return null;
    }

    return <Component node={node} />;
};
