// core-web/libs/sdk/angular/src/lib/components/dotcms-block-editor-renderer/blocks/grid-block.component.ts
import { NgComponentOutlet } from '@angular/common';
import { Component, Input } from '@angular/core';

import { BlockEditorNode } from '@dotcms/types';

import { CustomRenderer } from '../dotcms-block-editor-renderer.component';
import { DotCMSBlockEditorItemComponent } from '../item/dotcms-block-editor-item.component';

@Component({
    selector: 'dotcms-block-editor-renderer-grid-block',
    imports: [NgComponentOutlet],
    template: `
        <div
            data-type="gridBlock"
            class="grid-block"
            [style.display]="'grid'"
            [style.grid-template-columns]="gridTemplateColumns"
            [style.gap]="'1rem'">
            @for (column of node?.content; track $index) {
                <div data-type="gridColumn" class="grid-block__column">
                    <ng-container
                        *ngComponentOutlet="
                            blockEditorItem;
                            inputs: { content: column.content, customRenderers: customRenderers }
                        " />
                </div>
            }
        </div>
    `
})
export class DotGridBlock {
    @Input() node: BlockEditorNode | undefined;
    @Input() customRenderers: CustomRenderer | undefined;

    blockEditorItem = DotCMSBlockEditorItemComponent;

    get gridTemplateColumns(): string {
        const rawCols = Array.isArray(this.node?.attrs?.['columns'])
            ? this.node.attrs['columns']
            : [6, 6];
        const cols =
            rawCols.length === 2 &&
            rawCols.every((v: unknown) => typeof v === 'number' && Number.isFinite(v))
                ? rawCols
                : [6, 6];
        const pct1 = (cols[0] / 12) * 100;
        const pct2 = (cols[1] / 12) * 100;

        return `${pct1}% ${pct2}%`;
    }
}

// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/GridBlock.tsx
import { BlockEditorNode } from '@dotcms/types';

import { CustomRenderer } from '../../DotCMSBlockEditorRenderer';

interface GridBlockProps {
    node: BlockEditorNode;
    customRenderers?: CustomRenderer;
    blockEditorBlock: React.FC<{
        content: BlockEditorNode[] | undefined;
        customRenderers?: CustomRenderer;
    }>;
}

/**
 * Renders a grid block with two columns using a 12-column grid system.
 *
 * @param node - The grid block node containing column configuration.
 * @param blockEditorBlock - The block editor component for rendering nested content.
 * @param customRenderers - Optional custom renderers for nested blocks.
 */
export const GridBlock = ({ node, blockEditorBlock, customRenderers }: GridBlockProps) => {
    const BlockEditorBlockComponent = blockEditorBlock;
    const rawCols = Array.isArray(node.attrs?.columns) ? node.attrs.columns : [6, 6];
    const cols =
        rawCols.length === 2 &&
        rawCols.every((v: unknown) => typeof v === 'number' && Number.isFinite(v))
            ? rawCols
            : [6, 6];
    const pct1 = (cols[0] / 12) * 100;
    const pct2 = (cols[1] / 12) * 100;

    return (
        <div
            data-type="gridBlock"
            className="grid-block"
            style={
                {
                    display: 'grid',
                    gridTemplateColumns: `${pct1}% ${pct2}%`,
                    gap: '1rem'
                } as React.CSSProperties
            }>
            {node.content?.map((column, index) => (
                <div
                    key={`gridColumn-${index}`}
                    data-type="gridColumn"
                    className="grid-block__column">
                    <BlockEditorBlockComponent
                        content={column.content}
                        customRenderers={customRenderers}
                    />
                </div>
            ))}
        </div>
    );
};
