// core-web/libs/sdk/angular/next/components/dotcms-block-editor-renderer/blocks/table.component.ts
import { NgComponentOutlet } from '@angular/common';
import { Component, Input } from '@angular/core';

import { ContentNode } from '@dotcms/types';

import { DotCMSBlockEditorItemComponent } from '../item/dotcms-block-editor-item.component';
@Component({
    selector: 'dotcms-block-editor-renderer-table',
    standalone: true,
    imports: [NgComponentOutlet],
    template: `
        <table>
            <thead>
                @for (rowNode of content?.slice(0, 1); track rowNode.type) {
                    <tr>
                        @for (cellNode of rowNode.content; track cellNode.type) {
                            <th
                                [attr.colspan]="cellNode.attrs?.['colspan'] || 1"
                                [attr.rowspan]="cellNode.attrs?.['rowspan'] || 1">
                                <ng-container
                                    *ngComponentOutlet="
                                        blockEditorItem;
                                        inputs: { content: cellNode.content }
                                    "></ng-container>
                            </th>
                        }
                    </tr>
                }
            </thead>
            <tbody>
                @for (rowNode of content?.slice(1); track rowNode.type) {
                    <tr>
                        @for (cellNode of rowNode.content; track cellNode.type) {
                            <td
                                [attr.colspan]="cellNode.attrs?.['colspan'] || 1"
                                [attr.rowspan]="cellNode.attrs?.['rowspan'] || 1">
                                <ng-container
                                    *ngComponentOutlet="
                                        blockEditorItem;
                                        inputs: { content: cellNode.content }
                                    "></ng-container>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    `
})
export class DotTableBlock {
    @Input() content: ContentNode[] | undefined;
    blockEditorItem = DotCMSBlockEditorItemComponent;
}

// core-web/libs/sdk/react/src/lib/next/components/DotCMSBlockEditorRenderer/components/blocks/Table.tsx
import React from 'react';

import { BlockEditorNode } from '@dotcms/types';

interface TableRendererProps {
    content: BlockEditorNode[];
    blockEditorItem: React.FC<{
        content: BlockEditorNode[];
    }>;
}

/**
 * Renders a table component for the Block Editor.
 *
 * @param content - The content of the table.
 * @param blockEditorItem - The Block Editor item component.
 */
export const TableRenderer: React.FC<TableRendererProps> = ({
    content,
    blockEditorItem
}: TableRendererProps) => {
    const BlockEditorItemComponent = blockEditorItem;

    const renderTableContent = (node: BlockEditorNode) => {
        return <BlockEditorItemComponent content={node.content ?? []} />;
    };

    return (
        <table>
            <thead>
                {content.slice(0, 1).map((rowNode, rowIndex) => (
                    <tr key={`${rowNode.type}-${rowIndex}`}>
                        {rowNode.content?.map((cellNode, cellIndex) => (
                            <th
                                key={`${cellNode.type}-${cellIndex}`}
                                colSpan={Number(cellNode.attrs?.colspan || 1)}
                                rowSpan={Number(cellNode.attrs?.rowspan || 1)}>
                                {renderTableContent(cellNode)}
                            </th>
                        ))}
                    </tr>
                ))}
            </thead>
            <tbody>
                {content.slice(1).map((rowNode, rowIndex) => (
                    <tr key={`${rowNode.type}-${rowIndex}`}>
                        {rowNode.content?.map((cellNode, cellIndex) => (
                            <td
                                key={`${cellNode.type}-${cellIndex}`}
                                colSpan={Number(cellNode.attrs?.colspan || 1)}
                                rowSpan={Number(cellNode.attrs?.rowspan || 1)}>
                                {renderTableContent(cellNode)}
                            </td>
                        ))}
                    </tr>
                ))}
            </tbody>
        </table>
    );
};
